import { StyleSheet } from "react-native";
import { colors, fonts } from "@/constants/theme";
import { lab } from "./constants";

export const s = StyleSheet.create({
  // Back button
  backBtn:     { flexDirection: "row", alignItems: "center", alignSelf: "flex-start", gap: 6, marginBottom: 16, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.75)", borderWidth: 0.5, borderColor: "rgba(255,255,255,0.65)", shadowColor: "#0b1626", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.05, shadowRadius: 8 },
  backBtnText: { fontSize: 13, fontFamily: fonts.bold, color: lab.accent, letterSpacing: -0.2 },

  // Lab banner
  labBanner:     { borderRadius: 22, padding: 22, gap: 4, overflow: "hidden" },
  bannerCircle1: { position: "absolute", width: 170, height: 170, borderRadius: 85, backgroundColor: "rgba(255,255,255,0.04)", top: -50, right: -40 },
  bannerCircle2: { position: "absolute", width: 110, height: 110, borderRadius: 55, backgroundColor: "rgba(255,255,255,0.04)", bottom: -20, left: 10 },
  bannerTop:     { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  labIconWrap:   { width: 44, height: 44, borderRadius: 13, backgroundColor: "rgba(255,255,255,0.13)", alignItems: "center", justifyContent: "center" },
  bslBadge:      { flexDirection: "row", alignItems: "center", gap: 5, borderWidth: 1.5, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 4 },
  bslText:       { fontSize: 11, fontWeight: "900", letterSpacing: 0.5 },
  labAcro:       { fontSize: 10, fontWeight: "900", color: lab.soft + "99", letterSpacing: 2, textTransform: "uppercase" },
  labName:       { fontSize: 21, fontFamily: fonts.bold, color: "#fff", lineHeight: 27 },
  bannerMeta:    { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 8 },
  bannerMetaText: { fontSize: 12, color: lab.soft + "80" },
  bannerDot:     { width: 3, height: 3, borderRadius: 2, backgroundColor: lab.soft + "40" },
  onlineDot:     { width: 7, height: 7, borderRadius: 4 },

  // Stats
  statsRow:  { flexDirection: "row", gap: 10 },
  statPill:  { flex: 1, backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 12, alignItems: "center", gap: 4 },
  statVal:   { fontSize: 20, fontFamily: fonts.bold },
  statLabel: { fontSize: 10, color: colors.muted, textAlign: "center" },

  // Safety notice
  safetyNotice: { flexDirection: "row", alignItems: "flex-start", gap: 10, backgroundColor: lab.mid + "10", borderRadius: 12, padding: 12, borderWidth: 1, borderColor: lab.mid + "25" },
  safetyText:   { flex: 1, fontSize: 12, color: lab.mid, lineHeight: 16 },

  // Section label
  sectionLabel: { fontSize: 10, fontWeight: "900", letterSpacing: 1.5, color: colors.mutedSoft, textTransform: "uppercase", marginTop: 2 },

  // Group header
  groupHeader:      { flexDirection: "row" as const, alignItems: "center" as const, gap: 10, borderRadius: 12, borderWidth: 1, padding: 10 },
  groupHeaderIcon:  { width: 30, height: 30, borderRadius: 9, alignItems: "center" as const, justifyContent: "center" as const },
  groupHeaderLabel: { fontSize: 10, fontWeight: "900" as const, letterSpacing: 1.2, textTransform: "uppercase" as const },
  groupHeaderDesc:  { fontSize: 11, color: colors.muted, marginTop: 1 },

  // Module row
  labRow:        { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, flexDirection: "row" as const, alignItems: "center" as const, gap: 14, padding: 14, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 8 },
  labRowPressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
  labRowIcon:    { width: 48, height: 48, borderRadius: 14, alignItems: "center" as const, justifyContent: "center" as const, borderWidth: 1, flexShrink: 0, overflow: "hidden" as const },
  labRowLabel:   { fontSize: 15, fontFamily: fonts.bold, color: colors.ink, marginBottom: 2 },
  labRowSub:     { fontSize: 12, color: colors.muted, lineHeight: 16 },
  labRowChevron: { width: 28, height: 28, borderRadius: 8, alignItems: "center" as const, justifyContent: "center" as const, flexShrink: 0 },

  // Generic dashboard header
  genericHeader:      { flexDirection: "row" as const, alignItems: "center" as const, gap: 14, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: colors.primary + "20" },
  genericHeaderIcon:  { width: 48, height: 48, borderRadius: 14, backgroundColor: colors.primary + "18", alignItems: "center" as const, justifyContent: "center" as const },
  genericHeaderTitle: { fontSize: 18, fontFamily: fonts.bold, color: colors.ink },
  genericHeaderSub:   { fontSize: 12, color: colors.muted, marginTop: 2 },

  // Module header
  moduleHeader:   { flexDirection: "row", alignItems: "center", gap: 12 },
  moduleIconWrap: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" },
  moduleTitle:    { fontSize: 17, fontFamily: fonts.bold, color: colors.ink },
  moduleSub:      { fontSize: 12, color: colors.muted },

  // Filter row
  filterRow:           { flexDirection: "row", gap: 0, backgroundColor: "#f1f5f9", borderRadius: 10, padding: 3 },
  filterTab:           { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, paddingVertical: 8, borderRadius: 8 },
  filterTabActive:     { backgroundColor: "white", elevation: 2, shadowColor: "#000", shadowOpacity: 0.05, shadowRadius: 4 },
  filterTabText:       { fontSize: 13, fontFamily: fonts.bold, color: colors.mutedSoft },
  filterTabTextActive: { color: colors.ink },

  // Warn chip
  warnChip:     { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: lab.amber + "18", borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  warnChipText: { fontSize: 12, fontWeight: "900", color: lab.amber },

  // Empty
  emptyWrap: { alignItems: "center", paddingVertical: 32, gap: 12 },
  emptyText: { fontSize: 14, color: colors.muted, fontFamily: fonts.bold },

  // Inventory card
  invCard:      { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 5, padding: 16, gap: 10, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 6 },
  invTop:       { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  hazardBubble: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 7 },
  hazardEmoji:  { fontSize: 13 },
  hazardLabel:  { fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  stockBadge:   { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 7 },
  stockText:    { fontSize: 10, fontWeight: "900" },
  invName:      { fontSize: 16, fontFamily: fonts.bold, color: colors.ink, lineHeight: 21 },
  invMeta:      { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  metaChip:     { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#f8fafc", borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  metaChipText: { fontSize: 11, color: colors.muted },
  mono:         { fontFamily: "monospace" } as any,
  invDetail:    { gap: 2 },
  invDetailText: { fontSize: 11, color: colors.muted },
  expRow:       { flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "#f8fafc", borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 },
  expRowWarn:   { backgroundColor: lab.amber + "12" },
  expRowDanger: { backgroundColor: lab.danger + "12" },
  expText:      { fontSize: 11, fontFamily: fonts.bold },

  // Equipment list
  equipCard:        { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 12, overflow: "hidden", elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 6 },
  equipStatusStrip: { width: 5, alignSelf: "stretch" },
  equipIconWrap:    { width: 38, height: 38, borderRadius: 10, backgroundColor: "#f1f5f9", alignItems: "center", justifyContent: "center" },
  equipName:        { fontSize: 15, fontFamily: fonts.bold, color: colors.ink },
  equipModel:       { fontSize: 11, color: colors.muted },
  calBadge:         { fontSize: 10, fontWeight: "800" },
  equipStatusTag:   { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  equipStatusTagText: { fontSize: 10, fontWeight: "900" },

  // Equipment detail
  equipDetailBanner:   { borderRadius: 20, padding: 22 },
  equipStatusRow:      { flexDirection: "row", alignItems: "center", gap: 7, marginBottom: 10 },
  equipStatusDot:      { width: 9, height: 9, borderRadius: 5 },
  equipStatusLabel:    { fontSize: 11, fontWeight: "900", letterSpacing: 1 },
  equipDetailName:     { fontSize: 20, fontFamily: fonts.bold, color: "#fff", lineHeight: 26 },
  equipDetailModel:    { fontSize: 13, color: lab.soft + "99", marginTop: 2 },
  equipDetailSN:       { fontSize: 11, color: lab.soft + "70", marginTop: 4 },
  equipDetailMeta:     { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 8 },
  equipDetailMetaText: { fontSize: 12, color: lab.soft + "80" },

  // Calibration alert
  calAlert:     { flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderRadius: 12, borderWidth: 1 },
  calAlertText: { flex: 1, fontSize: 13, fontFamily: fonts.bold },

  // GLP log
  glpLogItem:     { flexDirection: "row", alignItems: "flex-start", gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.border },
  glpLogType:     { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4, minWidth: 38, alignItems: "center" },
  glpLogTypeText: { fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  glpLogDesc:     { fontSize: 13, color: colors.ink },
  glpLogDate:     { fontSize: 10, color: colors.mutedSoft, marginTop: 2 },

  // Lab Tools
  toolCard:      { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 16, flexDirection: "row", alignItems: "center", gap: 14, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 6 },
  toolIcon:      { width: 44, height: 44, borderRadius: 12, backgroundColor: lab.accent + "12", alignItems: "center", justifyContent: "center" },
  toolTitle:     { fontSize: 15, fontFamily: fonts.bold, color: colors.ink },
  toolDesc:      { fontSize: 12, color: colors.muted, lineHeight: 17 },
  toolBadge:     { backgroundColor: "#f1f5f9", paddingHorizontal: 8, paddingVertical: 3, borderRadius: 7 },
  toolBadgeText: { fontSize: 9, fontWeight: "900", color: colors.muted, textTransform: "uppercase" },

  // Add button
  addBtn: { width: 36, height: 36, borderRadius: 10, backgroundColor: lab.bio, alignItems: "center", justifyContent: "center" },

  // Create form
  createForm: { gap: 4 },
  fieldLabel: { fontSize: 11, fontWeight: "800", color: colors.muted, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 4, marginTop: 8 },
  fieldInput: { backgroundColor: "#f8fafc", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, borderColor: colors.border, fontSize: 15, color: colors.ink },
  textArea:   { minHeight: 80, textAlignVertical: "top" as const },

  // Chip
  chip:     { flexDirection: "row" as const, alignItems: "center" as const, gap: 5, backgroundColor: "#f1f5f9", borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7, borderWidth: 1, borderColor: colors.border },
  chipText: { fontSize: 12, fontFamily: fonts.bold, color: colors.muted },

  // Experiment cards
  expCard:           { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 5, padding: 16, gap: 8, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 6 },
  expCardTop:        { flexDirection: "row" as const, alignItems: "center" as const, gap: 8 },
  expStatusChip:     { flexDirection: "row" as const, alignItems: "center" as const, gap: 4, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  expStatusChipText: { fontSize: 10, fontWeight: "900" as const },
  expTypeTag:        { fontSize: 10, color: colors.mutedSoft, fontWeight: "800" as const, textTransform: "uppercase" as const, letterSpacing: 0.5 },
  expCardTitle:      { fontSize: 16, fontFamily: fonts.bold, color: colors.ink },
  expCardHypo:       { fontSize: 12, color: colors.muted, fontStyle: "italic" as const, lineHeight: 17 },
  expCardMeta:       { flexDirection: "row" as const, alignItems: "center" as const, gap: 6 },
  expCardMetaText:   { fontSize: 11, color: colors.mutedSoft },

  // Experiment detail banner
  expDetailBanner: { borderRadius: 20, padding: 22 },
  expStatusRow:    { flexDirection: "row" as const, alignItems: "center" as const, gap: 7, marginBottom: 10 },
  expStatusText:   { fontSize: 11, fontWeight: "900" as const, letterSpacing: 1 },
  expType:         { fontSize: 10, color: lab.soft + "70", fontWeight: "800" as const, textTransform: "uppercase" as const },
  expDetailTitle:  { fontSize: 20, fontFamily: fonts.bold, color: "#fff", lineHeight: 26 },
  expDetailHypo:   { fontSize: 13, color: lab.soft + "90", fontStyle: "italic" as const, lineHeight: 18, marginTop: 6 },
  expDateRow:      { flexDirection: "row" as const, alignItems: "center" as const, gap: 5, marginTop: 10 },
  expDateText:     { fontSize: 12, color: lab.soft + "80" },
  expDescCard:     { backgroundColor: "#f8fafc", borderRadius: 12, padding: 14, borderWidth: 1, borderColor: colors.border },
  expDescText:     { fontSize: 14, color: colors.ink, lineHeight: 20 },

  // Steps / SOP
  stepsProgress:     { height: 6, backgroundColor: "#f1f5f9", borderRadius: 3, overflow: "hidden" as const },
  stepsProgressFill: { height: 6, backgroundColor: lab.ok, borderRadius: 3 },
  stepRow:           { flexDirection: "row" as const, alignItems: "center" as const, gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  stepTitle:         { flex: 1, fontSize: 14, color: colors.ink },
  stepDone:          { textDecorationLine: "line-through" as const, color: colors.muted },

  // Danger zone
  dangerZone:  { borderRadius: 14, borderWidth: 1, borderColor: lab.danger + "30", backgroundColor: lab.danger + "05", padding: 16, gap: 12 },
  dangerTitle: { fontSize: 11, fontWeight: "900" as const, color: lab.danger, textTransform: "uppercase" as const, letterSpacing: 1 },

  // GLP type chips
  glpTypeChip:     { flexDirection: "row" as const, alignItems: "center" as const, gap: 5, backgroundColor: "#f1f5f9", borderRadius: 20, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: colors.border },
  glpTypeChipText: { fontSize: 12, fontFamily: fonts.bold, color: colors.muted },

  // GLP entry cards
  glpEntryCard:  { backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 4, padding: 14, gap: 8 },
  glpEntryTop:   { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "space-between" as const },
  glpEntryDate:  { fontSize: 11, color: colors.mutedSoft },
  glpEntryTitle: { fontSize: 15, fontFamily: fonts.bold, color: colors.ink },
  glpEntryBody:  { fontSize: 13, color: colors.muted, lineHeight: 18 },

  // Safety
  safetyBanner:       { borderRadius: 16, borderWidth: 1, padding: 16, gap: 10 },
  safetyBannerTop:    { flexDirection: "row" as const, alignItems: "center" as const, gap: 12 },
  safetyBannerIcon:   { width: 42, height: 42, borderRadius: 12, alignItems: "center" as const, justifyContent: "center" as const },
  safetyBannerTitle:  { fontSize: 16, fontFamily: fonts.bold },
  safetyBannerSub:    { fontSize: 12, color: colors.muted },
  safetyScoreRow:     { gap: 4, alignItems: "flex-end" as const },
  okScore:            { fontSize: 14, fontWeight: "900" as const, color: lab.ok },
  failScore:          { fontSize: 14, fontWeight: "900" as const, color: lab.danger },
  safetyProgress:     { height: 6, backgroundColor: "#f1f5f9", borderRadius: 3, overflow: "hidden" as const },
  safetyProgressFill: { height: 6, borderRadius: 3 },

  checkItem:     { backgroundColor: "white", borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 12, gap: 8 },
  checkItemFail: { borderColor: lab.danger + "50", backgroundColor: lab.danger + "04" },
  checkLabel:    { fontSize: 13, color: colors.ink, lineHeight: 18 },
  checkBtns:     { flexDirection: "row" as const, gap: 8 },
  checkBtn:      { flex: 1, paddingVertical: 7, borderRadius: 8, borderWidth: 1, borderColor: colors.border, alignItems: "center" as const, backgroundColor: "#f8fafc" },
  checkBtnOk:    { backgroundColor: lab.ok + "15", borderColor: lab.ok + "50" },
  checkBtnFail:  { backgroundColor: lab.danger + "15", borderColor: lab.danger + "50" },
  checkBtnNa:    { backgroundColor: "#f1f5f9", borderColor: colors.border },
  checkBtnText:  { fontSize: 11, fontWeight: "900" as const, color: colors.muted },

  inspectorInput:        { borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: 15, backgroundColor: "#fafafa" },
  safetyCompleteBtn:     { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 10, borderRadius: 14, paddingVertical: 16 },
  safetyCompleteBtnText: { fontSize: 16, fontFamily: fonts.bold, color: "white" },

  safetyTmpl:     { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 5, padding: 16, flexDirection: "row" as const, alignItems: "center" as const, gap: 12, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 6 },
  safetyTmplIcon: { width: 42, height: 42, borderRadius: 12, alignItems: "center" as const, justifyContent: "center" as const },
  safetyTmplName: { fontSize: 15, fontFamily: fonts.bold, color: colors.ink },
  safetyTmplSub:  { fontSize: 12, color: colors.muted },
  safetyTmplLast: { fontSize: 11, color: colors.mutedSoft },

  safetyDetailCard:    { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 16, gap: 10 },
  safetyDetailTop:     { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "space-between" as const },
  safetyDetailName:    { fontSize: 17, fontFamily: fonts.bold, color: colors.ink, flex: 1 },
  safetyScoreBig:      { borderRadius: 12, paddingHorizontal: 12, paddingVertical: 6 },
  safetyScoreBigText:  { fontSize: 18, fontWeight: "900" as const },
  safetyDetailMeta:    { fontSize: 12, color: colors.muted },
  safetyDetailStats:   { flexDirection: "row" as const, gap: 16 },
  safetyStatText:      { fontSize: 13, fontWeight: "800" as const },

  failItem:       { flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 10, paddingVertical: 6 },
  failItemText:   { flex: 1, fontSize: 13, color: lab.danger },
  detailItem:     { flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 10, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  detailItemResult: { fontSize: 14, fontWeight: "900" as const, width: 20 },
  detailItemLabel: { flex: 1, fontSize: 13, color: colors.ink, lineHeight: 18 },

  inspHistCard:  { backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: colors.border, flexDirection: "row" as const, alignItems: "center" as const, gap: 12, padding: 12, elevation: 1 },
  inspHistLeft:  { width: 52, height: 52, borderRadius: 13, alignItems: "center" as const, justifyContent: "center" as const },
  inspHistPct:   { fontSize: 16, fontWeight: "900" as const },
  inspHistName:  { fontSize: 14, fontFamily: fonts.bold, color: colors.ink },
  inspHistMeta:  { fontSize: 11, color: colors.muted },

  removeInspBtn:     { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 8, borderWidth: 1, borderColor: lab.danger + "50", borderRadius: 12, paddingVertical: 10 },
  removeInspBtnText: { fontSize: 14, fontFamily: fonts.bold, color: lab.danger },

  // Analytics module
  kpiRow:             { flexDirection: "row" as const, gap: 8, marginBottom: 4 },
  kpiCard:            { flex: 1, backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 10, alignItems: "center" as const, gap: 3, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 5 },
  kpiValue:           { fontSize: 20, fontFamily: fonts.bold },
  kpiLabel:           { fontSize: 9, color: colors.muted, textAlign: "center" as const },
  analyticsCard:      { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 16, gap: 12, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 6 },
  analyticsCardHeader: { flexDirection: "row" as const, alignItems: "center" as const, gap: 7 },
  analyticsCardTitle:  { fontSize: 13, fontFamily: fonts.bold, color: colors.ink },
  analyticsDonutRow:   { flexDirection: "row" as const, alignItems: "center" as const, gap: 16 },
  donutBigNum:         { fontSize: 18, fontFamily: fonts.bold, textAlign: "center" as const },
  donutBigSub:         { fontSize: 9, color: colors.muted, textAlign: "center" as const },
  analyticsListItem:   { flexDirection: "row" as const, alignItems: "center" as const, gap: 8, paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: "#f8fafc" },
  analyticsListDot:    { width: 8, height: 8, borderRadius: 4 },
  analyticsListName:   { flex: 1, fontSize: 13, color: colors.ink },
  analyticsListBadge:  { fontSize: 11, fontWeight: "900" as const, color: colors.muted },
  activityRow:         { flexDirection: "row" as const, alignItems: "center" as const, gap: 8, paddingVertical: 4 },
  activityLabel:       { width: 90, fontSize: 12, color: colors.muted },
  activityBarWrap:     { flex: 1, height: 8, backgroundColor: "#f1f5f9", borderRadius: 4, overflow: "hidden" as const },
  activityBar:         { height: 8, borderRadius: 4 },
  activityCount:       { width: 24, fontSize: 12, fontWeight: "900" as const, textAlign: "right" as const },
  successBadge:        { backgroundColor: "#7c3aed18", borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3 },
  successBadgeText:    { fontSize: 10, fontWeight: "900" as const, color: "#7c3aed" },
  glpKpi:              { flex: 1, alignItems: "center" as const, gap: 2 },
  glpKpiNum:           { fontSize: 22, fontFamily: fonts.bold },
  glpKpiLabel:         { fontSize: 10, color: colors.muted, textAlign: "center" as const },
  inspScoreCircle:     { width: 60, height: 60, borderRadius: 30, borderWidth: 3, alignItems: "center" as const, justifyContent: "center" as const },
  inspScoreNum:        { fontSize: 16, fontWeight: "900" as const },
  inspScoreLabel:      { fontSize: 13, fontFamily: fonts.bold, color: colors.ink },
  inspScoreDate:       { fontSize: 11, color: colors.muted, marginTop: 2, marginBottom: 6 },

  // Access Control module
  accessStatusCard:    { flexDirection: "row" as const, alignItems: "center" as const, gap: 14, borderRadius: 18, padding: 18, borderWidth: 1, borderColor: colors.border },
  accessStatusIcon:    { width: 56, height: 56, borderRadius: 16, alignItems: "center" as const, justifyContent: "center" as const },
  accessStatusTitle:   { fontSize: 17, fontFamily: fonts.bold },
  accessStatusSub:     { fontSize: 12, color: colors.muted, marginTop: 3 },
  bslIndicator:        { borderWidth: 1.5, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 5, alignSelf: "flex-start" as const },
  bslIndicatorText:    { fontSize: 12, fontFamily: fonts.bold },
  bslChip:             { flex: 1, alignItems: "center" as const, justifyContent: "center" as const, paddingVertical: 10, borderRadius: 10, borderWidth: 1.5, backgroundColor: "white" },
  bslChipText:         { fontSize: 12, fontFamily: fonts.bold },
  accessToggleBtn:     { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 10, borderRadius: 16, paddingVertical: 17 },
  accessToggleBtnText: { fontSize: 16, fontFamily: fonts.bold, color: "white" },
  accessLogCard:       { backgroundColor: "white", borderRadius: 13, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 4, flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 12, padding: 12, elevation: 1 },
  accessLogIcon:       { width: 34, height: 34, borderRadius: 10, alignItems: "center" as const, justifyContent: "center" as const, flexShrink: 0 },
  accessLogAction:     { fontSize: 14, fontFamily: fonts.bold, color: colors.ink },
  accessLogUser:       { fontSize: 12, color: colors.muted, marginTop: 2 },
  accessLogNotes:      { fontSize: 11, color: colors.mutedSoft, fontStyle: "italic" as const, marginTop: 2 },
  accessLogTime:       { fontSize: 10, color: colors.mutedSoft, fontFamily: fonts.bold, flexShrink: 0 },
  bslMicroBadge:       { borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  bslMicroText:        { fontSize: 10, fontWeight: "900" as const },
  accessEqCard:        { backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 4, flexDirection: "row" as const, alignItems: "center" as const, gap: 12, padding: 14, elevation: 1 },
  accessEqName:        { fontSize: 14, fontFamily: fonts.bold, color: colors.ink, flex: 1 },
  accessEqSub:         { fontSize: 11, color: colors.muted, marginTop: 2 },
  bslStepBtn:          { width: 28, height: 28, borderRadius: 7, borderWidth: 1, alignItems: "center" as const, justifyContent: "center" as const },
  bslStepText:         { fontSize: 10, fontWeight: "900" as const },

  // Lab Calendar module
  calendarWidget:    { borderRadius: 16, overflow: "hidden" as const, borderWidth: 1, borderColor: colors.border, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 6 },
  bookingCard:       { backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: colors.border, flexDirection: "row" as const, gap: 12, padding: 14, elevation: 1 },
  bookingTimeCol:    { alignItems: "center" as const, gap: 4, width: 44 },
  bookingStart:      { fontSize: 12, fontFamily: fonts.bold, color: "#0891b2" },
  bookingEnd:        { fontSize: 12, fontFamily: fonts.bold, color: colors.muted },
  bookingTimeLine:   { flex: 1, width: 1.5, backgroundColor: "#0891b230", minHeight: 16 },
  bookingEqName:     { fontSize: 14, fontFamily: fonts.bold, color: colors.ink, flex: 1 },
  bookingPurpose:    { fontSize: 12, color: colors.muted, lineHeight: 16 },
  bookingUser:       { fontSize: 11, color: colors.muted },
  bookingCancelBtn:  { width: 28, height: 28, borderRadius: 8, backgroundColor: lab.danger + "10", alignItems: "center" as const, justifyContent: "center" as const, alignSelf: "flex-start" as const },
  formLabel:         { fontSize: 12, fontFamily: fonts.bold, color: colors.muted, textTransform: "uppercase" as const, letterSpacing: 0.5 },
  formInput:         { borderWidth: 1, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: colors.ink, backgroundColor: "#fafafa" },
  eqPickerRow:       { flexDirection: "row" as const, alignItems: "center" as const, gap: 10, backgroundColor: "white", borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 12 },
  eqPickerRowActive: { borderColor: "#0891b240", backgroundColor: "#0891b208" },
  eqPickerDot:       { width: 10, height: 10, borderRadius: 5 },
  eqPickerLabel:     { flex: 1, fontSize: 14, color: colors.ink },
  timePickerWrap:    { flexDirection: "row" as const, flexWrap: "wrap" as const, gap: 6 },
  timeChip:          { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, backgroundColor: "#f1f5f9", borderWidth: 1, borderColor: colors.border },
  timeChipActive:    { backgroundColor: "#0891b214", borderColor: "#0891b240" },
  timeChipText:      { fontSize: 12, color: colors.muted, fontFamily: fonts.bold },

  // Notifications module
  notifPermCard:      { flexDirection: "row" as const, alignItems: "center" as const, gap: 12, borderWidth: 1.5, borderRadius: 16, padding: 14 },
  notifPermIcon:      { width: 46, height: 46, borderRadius: 13, alignItems: "center" as const, justifyContent: "center" as const },
  notifPermTitle:     { fontSize: 14, fontFamily: fonts.bold },
  notifPermSub:       { fontSize: 11, color: colors.muted, lineHeight: 15, marginTop: 2 },
  notifPermBtn:       { backgroundColor: "#ea580c", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8 },
  notifPermBtnText:   { fontSize: 12, fontFamily: fonts.bold, color: "white" },
  notifSyncBadge:     { flexDirection: "row" as const, alignItems: "center" as const, gap: 4, backgroundColor: lab.ok + "12", borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  notifSyncText:      { fontSize: 10, fontFamily: fonts.bold, color: lab.ok },
  notifSummaryRow:    { flexDirection: "row" as const, gap: 10 },
  notifSummaryCard:   { flex: 1, backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 12, alignItems: "center" as const, gap: 6, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 5 },
  notifSummaryIcon:   { width: 38, height: 38, borderRadius: 11, alignItems: "center" as const, justifyContent: "center" as const, overflow: "hidden" as const },
  notifSummaryNum:    { fontSize: 22, fontFamily: fonts.bold, color: colors.ink },
  notifSummarySub:    { fontSize: 9, color: colors.muted, textAlign: "center" as const, lineHeight: 13 },
  notifActionBtn:     { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 10, borderRadius: 14, paddingVertical: 15 },
  notifActionBtnText: { fontSize: 15, fontFamily: fonts.bold, color: "white" },
  notifItem:          { backgroundColor: "white", borderRadius: 13, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 4, flexDirection: "row" as const, alignItems: "center" as const, gap: 12, padding: 12, elevation: 1 },
  notifItemIcon:      { width: 34, height: 34, borderRadius: 10, alignItems: "center" as const, justifyContent: "center" as const },
  notifItemTitle:     { fontSize: 13, fontFamily: fonts.bold, color: colors.ink },
  notifItemBody:      { fontSize: 11, color: colors.muted, marginTop: 1 },
  notifItemDate:      { fontSize: 10, color: colors.mutedSoft, fontFamily: fonts.bold },
  notifInfoCard:      { flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 8, backgroundColor: "#0369a110", borderRadius: 12, borderWidth: 1, borderColor: "#0369a128", padding: 12 },
  notifInfoText:      { flex: 1, fontSize: 11, color: "#0369a1", lineHeight: 16 },

  // Reports module
  reportInfoBanner: { flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 10, backgroundColor: "#0369a115", borderRadius: 12, borderWidth: 1, borderColor: "#0369a130", padding: 12 },
  reportInfoText:   { flex: 1, fontSize: 12, color: "#0369a1", lineHeight: 17 },
  reportCard:       { backgroundColor: "white", borderRadius: 18, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 5, flexDirection: "row" as const, alignItems: "center" as const, gap: 14, padding: 16, elevation: 3, shadowColor: "#000", shadowOpacity: 0.05, shadowRadius: 8 },
  reportCardIcon:   { width: 50, height: 50, borderRadius: 14, alignItems: "center" as const, justifyContent: "center" as const, overflow: "hidden" as const },
  reportCardTitle:  { fontSize: 15, fontFamily: fonts.bold, color: colors.ink },
  reportCardSub:    { fontSize: 11, color: colors.muted, lineHeight: 15, marginTop: 2 },
  reportCountBadge: { alignSelf: "flex-start" as const, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, marginTop: 6 },
  reportCountText:  { fontSize: 10, fontWeight: "900" as const },
  reportBtnWrap:    { marginLeft: "auto" as const },
  reportBtn:           { width: 38, height: 38, borderRadius: 12, alignItems: "center" as const, justifyContent: "center" as const },
  reportFooter:        { flexDirection: "row" as const, alignItems: "center" as const, gap: 8, paddingVertical: 12 },
  reportFooterText:    { fontSize: 11, color: colors.mutedSoft },
  reportReadyCard:     { flexDirection: "row" as const, alignItems: "center" as const, gap: 12, backgroundColor: "#f0fdf4", borderRadius: 14, borderWidth: 1.5, borderColor: "#86efac", padding: 14 },
  reportReadyTitle:    { fontSize: 13, fontWeight: "700" as const, color: "#166534" },
  reportReadySub:      { fontSize: 11, color: "#4ade80" },
  reportActionBtn:     { flexDirection: "row" as const, alignItems: "center" as const, gap: 5, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 7 },
  reportActionBtnText: { fontSize: 12, fontWeight: "700" as const, color: "white" },
  zenodoSection:       { backgroundColor: "#faf5ff", borderRadius: 16, borderWidth: 1.5, borderColor: "#e9d5ff", padding: 16, gap: 0 },
  zenodoTitle:         { fontSize: 14, fontWeight: "700" as const, color: "#6d28d9" },
  zenodoDesc:          { fontSize: 12, color: "#6d28d9aa", lineHeight: 17, marginBottom: 12 },
  zenodoBtn:           { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 8, backgroundColor: "#7c3aed", borderRadius: 12, paddingVertical: 10, paddingHorizontal: 16 },
  zenodoBtnText:       { fontSize: 13, fontWeight: "700" as const, color: "white" },

  // Waste module
  wasteCard:              { backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 5, padding: 14, gap: 10, elevation: 2, shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 6 },
  wasteCardTop:           { flexDirection: "row" as const, alignItems: "center" as const, gap: 10 },
  wasteIconWrap:          { width: 38, height: 38, borderRadius: 11, alignItems: "center" as const, justifyContent: "center" as const },
  wasteName:              { fontSize: 15, fontFamily: fonts.bold, color: colors.ink },
  wasteMeta:              { fontSize: 11, color: colors.muted },
  wasteDate:              { fontSize: 10, color: colors.mutedSoft, fontFamily: fonts.bold },
  wasteDetails:           { gap: 5, paddingLeft: 48 },
  wasteDetailRow:         { flexDirection: "row" as const, alignItems: "center" as const, gap: 6 },
  wasteDetailText:        { fontSize: 12, color: colors.muted },
  wasteNotes:             { fontSize: 11, color: colors.mutedSoft, fontStyle: "italic" as const },
  wasteCatChip:           { flexDirection: "row" as const, alignItems: "center" as const, gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, borderWidth: 1.5, borderColor: colors.border, backgroundColor: "#f8fafc" },
  wasteCatText:           { fontSize: 12, color: colors.muted },
  wasteSubmitBtn:         { flexDirection: "row" as const, alignItems: "center" as const, justifyContent: "center" as const, gap: 10, backgroundColor: "#0d9488", borderRadius: 14, paddingVertical: 16, marginTop: 8 },
  wasteSubmitBtnText:     { fontSize: 16, fontFamily: fonts.bold, color: "white" },
  wasteReportBanner:      { borderRadius: 18, padding: 20, gap: 2, marginBottom: 4 },
  wasteReportBannerTitle: { fontSize: 18, fontFamily: fonts.bold, color: "white" },
  wasteReportBannerSub:   { fontSize: 12, color: "rgba(255,255,255,0.7)" },
  wasteReportBigNum:      { fontSize: 28, fontFamily: fonts.bold, color: "white" },
  wasteReportBigLabel:    { fontSize: 11, color: "rgba(255,255,255,0.7)" },
  wasteCatReportCard:     { backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 14, flexDirection: "row" as const, alignItems: "center" as const, gap: 12, elevation: 1 },
  wasteCatReportName:     { fontSize: 14, fontFamily: fonts.bold, color: colors.ink },
  wasteCatReportCount:    { fontSize: 13, fontWeight: "900" as const },
  wasteProgBar:           { height: 6, backgroundColor: "#f1f5f9", borderRadius: 3, overflow: "hidden" as const },
  wasteProgFill:          { height: 6, borderRadius: 3 },
  wasteComplianceCard:    { flexDirection: "row" as const, alignItems: "flex-start" as const, gap: 10, backgroundColor: "#0d948810", borderRadius: 12, borderWidth: 1, borderColor: "#0d948830", padding: 12 },
  wasteComplianceText:    { flex: 1, fontSize: 12, color: "#0f5c50", lineHeight: 17 },
  dropdown:     { position: "absolute" as const, top: 44, left: 0, right: 0, backgroundColor: "white", borderRadius: 10, borderWidth: 1, borderColor: colors.border, zIndex: 200, elevation: 15, shadowColor: "#000", shadowOpacity: 0.1, shadowRadius: 8 },
  dropdownItem: { paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  dropdownText: { fontSize: 14, color: colors.ink },

  // Diary
  inputTitle:    { fontSize: 16, fontFamily: fonts.bold, borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: 8, marginBottom: 12 },
  inputText:     { minHeight: 120, backgroundColor: "#f8fafc", borderRadius: 12, padding: 12, fontSize: 14, marginBottom: 16 },
  historyItem:   { flexDirection: "row", backgroundColor: "white", borderRadius: 16, borderWidth: 1, borderColor: colors.border, overflow: "hidden" },
  historyAccent: { width: 4 },
  historyContent: { flex: 1, padding: 14, gap: 4 },
  historyTitle:  { fontSize: 15, fontFamily: fonts.bold },
  historyBody:   { fontSize: 13, color: colors.muted, lineHeight: 18 },
  historyDate:   { fontSize: 10, color: colors.mutedSoft, marginTop: 4 },

  // Chat
  chatContainer: { flex: 1, minHeight: 500, backgroundColor: "white", borderRadius: 20, overflow: "hidden", borderWidth: 1, borderColor: colors.border },
  msgWrapper:    { paddingHorizontal: 12, paddingVertical: 4 },
  msgOwn:        { alignItems: "flex-end" },
  msgOther:      { alignItems: "flex-start" },
  msgBubble:     { maxWidth: "80%", padding: 12, borderRadius: 18 },
  bubbleOwn:     { backgroundColor: colors.primary, borderBottomRightRadius: 4 },
  bubbleOther:   { backgroundColor: "#f1f5f9", borderBottomLeftRadius: 4, borderWidth: 1, borderColor: colors.border },
  msgAuthor:     { fontSize: 10, fontWeight: "800", marginBottom: 2, color: "rgba(0,0,0,0.3)" },
  msgContent:    { fontSize: 15, color: colors.ink, lineHeight: 20 },
  msgTime:       { fontSize: 9, color: colors.mutedSoft, marginTop: 4, alignSelf: "flex-end" },
  chatInputRow:  { flexDirection: "row", padding: 12, backgroundColor: "white", borderTopWidth: 1, borderTopColor: colors.border, gap: 10, alignItems: "center" },
  chatInput:     { flex: 1, backgroundColor: "#f8fafc", borderRadius: 20, paddingHorizontal: 16, paddingVertical: 10, maxHeight: 100, borderWidth: 1, borderColor: colors.border },
  sendBtn:       { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
});
