// ─── Equipment Catalog — classified reference database ────────────────────────

export type CatalogCategory = {
  id: string;
  label: string;
  labelShort: string;
  emoji: string;
  color: string;
};

export type CatalogItem = {
  id: string;
  categoryId: string;
  name: string;
  nameEn: string;
  emoji: string;
  description: string;
  manufacturers: string[];
  calibrationDays: number;   // 0 = no periodic calibration
  maintenanceDays: number;   // 0 = no periodic maintenance
  requiresCert: boolean;
  bslMax: 1 | 2 | 3 | 4;
  specs: Record<string, string>;
  usageNotes?: string;
};

// ─── Categories ───────────────────────────────────────────────────────────────
export const CATALOG_CATEGORIES: CatalogCategory[] = [
  { id: "weighing",        label: "Зважування",         labelShort: "Ваги",       emoji: "⚖️",  color: "#0369a1" },
  { id: "centrifugation",  label: "Центрифугування",     labelShort: "Центрифуги", emoji: "🌀",  color: "#7c3aed" },
  { id: "microscopy",      label: "Мікроскопія",         labelShort: "Мікроскопи", emoji: "🔬",  color: "#0f766e" },
  { id: "spectroscopy",    label: "Спектроскопія",        labelShort: "Спектро",    emoji: "🌈",  color: "#b45309" },
  { id: "chromatography",  label: "Хроматографія",        labelShort: "Хромат.",    emoji: "📈",  color: "#be123c" },
  { id: "molecular_bio",   label: "Молекулярна біол.",   labelShort: "Мол. біол.", emoji: "🧬",  color: "#0891b2" },
  { id: "thermal",         label: "Термічне",             labelShort: "Термо",      emoji: "🌡️", color: "#d97706" },
  { id: "cold_storage",    label: "Кріосховище",          labelShort: "Кріо",       emoji: "🧊",  color: "#2563eb" },
  { id: "mixing",          label: "Перемішування",        labelShort: "Мішалки",    emoji: "🔄",  color: "#059669" },
  { id: "solution",        label: "Аналіз розчинів",     labelShort: "Розчини",    emoji: "💧",  color: "#0369a1" },
  { id: "safety_air",      label: "Захист повітря",       labelShort: "Захист",     emoji: "🛡️", color: "#dc2626" },
  { id: "dispensing",      label: "Дозування рідин",     labelShort: "Піпетки",    emoji: "💉",  color: "#6d28d9" },
  { id: "electrochemistry",label: "Електрохімія",         labelShort: "Електро",    emoji: "⚡",  color: "#ca8a04" },
  { id: "xray_nuclear",    label: "Рентген / Ядерне",    labelShort: "Рентген",    emoji: "☢️",  color: "#9f1239" },
  { id: "general",         label: "Загальне",             labelShort: "Загальне",   emoji: "🔧",  color: "#64748b" },
];

// ─── Catalog items ────────────────────────────────────────────────────────────
export const CATALOG_ITEMS: CatalogItem[] = [

  // ── ЗВАЖУВАННЯ ──────────────────────────────────────────────────────────────
  {
    id: "analytical_balance",
    categoryId: "weighing",
    name: "Аналітичні ваги",
    nameEn: "Analytical Balance",
    emoji: "⚖️",
    description: "Прецизійні ваги для точного зважування речовин з точністю до 0.1 мг.",
    manufacturers: ["Sartorius", "Mettler Toledo", "Shimadzu", "OHAUS"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 4,
    specs: { "Дискретність": "0.0001 г", "Макс. навантаження": "220 г", "Час стабілізації": "~5 с" },
    usageNotes: "Вимагають внутрішнього або зовнішнього калібрування, захисту від вібрацій та протягів.",
  },
  {
    id: "precision_balance",
    categoryId: "weighing",
    name: "Точні ваги",
    nameEn: "Precision Balance",
    emoji: "⚖️",
    description: "Ваги загального призначення, точність до 10 мг. Для зважування великих мас.",
    manufacturers: ["Sartorius", "Mettler Toledo", "OHAUS", "Adam Equipment"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 4,
    specs: { "Дискретність": "0.01 г", "Макс. навантаження": "2000 г" },
  },
  {
    id: "microbalance",
    categoryId: "weighing",
    name: "Мікроваги",
    nameEn: "Microbalance / Ultramicrobalance",
    emoji: "⚖️",
    description: "Ультраточні ваги для зважування мікро- та нанограмових кількостей речовини.",
    manufacturers: ["Sartorius (SE2)", "Mettler Toledo (XP6U)", "Citizen"],
    calibrationDays: 180,
    maintenanceDays: 30,
    requiresCert: true,
    bslMax: 4,
    specs: { "Дискретність": "0.000001 г (1 мкг)", "Макс. навантаження": "6.1 г" },
    usageNotes: "Потребують ізольованого приміщення від вібрацій; внутрішнє автокалібрування.",
  },
  {
    id: "density_meter",
    categoryId: "weighing",
    name: "Денситометр",
    nameEn: "Density Meter",
    emoji: "📏",
    description: "Вимірює густину рідин методом осцилюючої U-трубки.",
    manufacturers: ["Anton Paar (DMA)", "Mettler Toledo", "Rudolph Research"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон": "0–3 г/см³", "Точність": "±0.0001 г/см³", "Температурний діапазон": "0–100°C" },
  },
  {
    id: "refractometer",
    categoryId: "weighing",
    name: "Рефрактометр",
    nameEn: "Refractometer",
    emoji: "📏",
    description: "Вимірює показник заломлення розчинів; застосовується для визначення концентрацій.",
    manufacturers: ["Anton Paar (Abbemat)", "ATAGO", "Mettler Toledo"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон nD": "1.3000–1.7000", "Точність": "±0.0001 nD" },
  },

  // ── ЦЕНТРИФУГУВАННЯ ──────────────────────────────────────────────────────────
  {
    id: "microcentrifuge",
    categoryId: "centrifugation",
    name: "Мікроцентрифуга",
    nameEn: "Microcentrifuge",
    emoji: "🌀",
    description: "Для центрифугування мікропробірок (0.2–2 мл) з високою швидкістю.",
    manufacturers: ["Eppendorf", "Thermo Fisher", "Sartorius", "Hettich"],
    calibrationDays: 365,
    maintenanceDays: 365,
    requiresCert: false,
    bslMax: 2,
    specs: { "Макс. швидкість": "15 000–21 000 об/хв", "RCF макс": "до 21 130 × g", "Об'єм": "0.2–2 мл" },
  },
  {
    id: "refrigerated_centrifuge",
    categoryId: "centrifugation",
    name: "Рефрижераторна центрифуга",
    nameEn: "Refrigerated Centrifuge",
    emoji: "🌀",
    description: "Центрифуга з охолодженням для термочутливих зразків.",
    manufacturers: ["Eppendorf (5804R)", "Thermo Fisher (Sorvall)", "Beckman Coulter", "Hettich"],
    calibrationDays: 365,
    maintenanceDays: 365,
    requiresCert: true,
    bslMax: 2,
    specs: { "Температурний діапазон": "-20…+40°C", "Макс. швидкість": "21 000 об/хв", "Ротор": "Качалка, кут" },
  },
  {
    id: "ultracentrifuge",
    categoryId: "centrifugation",
    name: "Ультрацентрифуга",
    nameEn: "Ultracentrifuge",
    emoji: "🌀",
    description: "Препаративна або аналітична, для розділення субклітинних компонентів.",
    manufacturers: ["Beckman Coulter (Optima)", "Thermo Fisher (WX)"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 3,
    specs: { "Макс. швидкість": "до 150 000 об/хв", "RCF макс": "до 1 000 000 × g" },
    usageNotes: "Потребує сертифікованого ротора та спеціального обслуговування.",
  },

  // ── МІКРОСКОПІЯ ──────────────────────────────────────────────────────────────
  {
    id: "light_microscope",
    categoryId: "microscopy",
    name: "Світловий мікроскоп",
    nameEn: "Light / Optical Microscope",
    emoji: "🔬",
    description: "Стандартний оптичний мікроскоп для клітинних і тканинних препаратів.",
    manufacturers: ["Zeiss (Axio)", "Leica (DM)", "Nikon (Eclipse)", "Olympus (BX)"],
    calibrationDays: 0,
    maintenanceDays: 365,
    requiresCert: false,
    bslMax: 2,
    specs: { "Збільшення": "40–1000×", "Конденсор": "Abbe", "Освітлення": "LED/Галоген" },
  },
  {
    id: "fluorescence_microscope",
    categoryId: "microscopy",
    name: "Флуоресцентний мікроскоп",
    nameEn: "Fluorescence Microscope",
    emoji: "🔬",
    description: "Мікроскоп з джерелами збудження для флуоресцентних барвників та GFP-мічених зразків.",
    manufacturers: ["Zeiss (Axio Observer)", "Leica (DMLB)", "Nikon (Ti2)", "Olympus (IX)"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Фільтри": "DAPI, FITC, TRITC, Cy5", "Джерело": "LED/Ртутна лампа", "Збільшення": "до 1000×" },
  },
  {
    id: "confocal_microscope",
    categoryId: "microscopy",
    name: "Конфокальний мікроскоп",
    nameEn: "Confocal Laser Scanning Microscope",
    emoji: "🔬",
    description: "Лазерний конфокальний мікроскоп для 3D-реконструкції та коло-локалізаційного аналізу.",
    manufacturers: ["Zeiss (LSM)", "Leica (STELLARIS)", "Nikon (A1)", "Olympus (FV)"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 2,
    specs: { "Лазери": "405, 488, 543, 633 нм", "Роздільна здатність": "≤200 нм (XY)", "Детектори": "PMT / GaAsP" },
  },
  {
    id: "sem",
    categoryId: "microscopy",
    name: "Скануючий електронний мікроскоп (СЕМ)",
    nameEn: "Scanning Electron Microscope (SEM)",
    emoji: "🔬",
    description: "Для дослідження поверхні зразків з нанометровою роздільною здатністю.",
    manufacturers: ["Zeiss (EVO)", "FEI/Thermo Fisher (Quanta)", "Hitachi", "JEOL"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 1,
    specs: { "Роздільна здатність": "1–20 нм", "Напруга": "0.2–30 кВ", "EDX": "Опціонально" },
  },
  {
    id: "tem",
    categoryId: "microscopy",
    name: "Трансмісійний електронний мікроскоп (ТЕМ)",
    nameEn: "Transmission Electron Microscope (TEM)",
    emoji: "🔬",
    description: "Для структурного аналізу надтонких зрізів з атомарною роздільною здатністю.",
    manufacturers: ["FEI/Thermo Fisher (Tecnai)", "JEOL (JEM)", "Hitachi (H)"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 1,
    specs: { "Роздільна здатність": "~0.1 нм", "Напруга": "80–300 кВ" },
  },
  {
    id: "afm",
    categoryId: "microscopy",
    name: "Атомно-силовий мікроскоп (АСМ)",
    nameEn: "Atomic Force Microscope (AFM)",
    emoji: "🔬",
    description: "Скануюча зондова мікроскопія — топографія поверхні з нанометровою точністю.",
    manufacturers: ["Bruker (Dimension)", "Asylum Research (Cypher)", "NT-MDT", "Park Systems"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: false,
    bslMax: 1,
    specs: { "Роздільна здатність (Z)": "~0.03 нм", "Режими": "Contact, Tapping, PeakForce" },
  },
  {
    id: "stereomicroscope",
    categoryId: "microscopy",
    name: "Стереомікроскоп",
    nameEn: "Stereo / Dissecting Microscope",
    emoji: "🔬",
    description: "Бінокулярний мікроскоп для препарування, якісного контролю та роботи з дрібними об'єктами.",
    manufacturers: ["Zeiss (Stemi)", "Leica (S9)", "Nikon (SMZ)", "Olympus (SZ)"],
    calibrationDays: 0,
    maintenanceDays: 365,
    requiresCert: false,
    bslMax: 2,
    specs: { "Збільшення": "7–45×", "Поле зору": "до 30 мм", "Освітлення": "Кільцевий LED" },
  },

  // ── СПЕКТРОСКОПІЯ ─────────────────────────────────────────────────────────────
  {
    id: "uv_vis_spectrophotometer",
    categoryId: "spectroscopy",
    name: "УФ-Видимий спектрофотометр",
    nameEn: "UV-Vis Spectrophotometer",
    emoji: "🌈",
    description: "Вимірює поглинання/пропускання у діапазоні 190–1100 нм. Стандарт для кількісного аналізу.",
    manufacturers: ["Shimadzu (UV-1900)", "Thermo Fisher (NanoDrop)", "Agilent (Cary)", "Hach"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон": "190–1100 нм", "Точність λ": "±0.3 нм", "Мікрооб'єм": "1 мкл (NanoDrop)" },
  },
  {
    id: "ftir",
    categoryId: "spectroscopy",
    name: "ІЧ-Фур'є спектрометр (FTIR)",
    nameEn: "Fourier-Transform Infrared Spectrometer",
    emoji: "🌈",
    description: "Ідентифікація функціональних груп, контроль якості, структурний аналіз.",
    manufacturers: ["Bruker (Alpha, Vertex)", "Thermo Fisher (Nicolet)", "Agilent", "PerkinElmer"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон": "4000–400 см⁻¹", "Роздільна здатність": "до 0.25 см⁻¹", "ATR": "Одноразовий / Мультиразовий" },
  },
  {
    id: "raman_spectrometer",
    categoryId: "spectroscopy",
    name: "Раман-спектрометр",
    nameEn: "Raman Spectrometer",
    emoji: "🌈",
    description: "Неруйнівна ідентифікація матеріалів, аналіз кристалічних структур та сумішей.",
    manufacturers: ["Renishaw", "Horiba (LabRAM)", "Bruker (Senterra)", "Thermo Fisher (DXR)"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Лазер": "532, 633, 785 нм", "Спектральний діапазон": "100–3500 см⁻¹" },
  },
  {
    id: "aas",
    categoryId: "spectroscopy",
    name: "Атомно-абсорбційний спектрометр (ААС)",
    nameEn: "Atomic Absorption Spectrometer (AAS)",
    emoji: "🌈",
    description: "Визначення мікроконцентрацій металів у розчинах. Полум'яний або графітовий варіант.",
    manufacturers: ["Thermo Fisher (iCE)", "PerkinElmer (PinAAcle)", "Agilent (240)", "GBC"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 2,
    specs: { "Елементи": ">60 металів", "Нижня межа": "мкг/л (ГФ)", "Варіант": "Полум'яний / ЕТА" },
    usageNotes: "Полум'яний варіант вимагає ацетилен/повітря; ЕТА — спеціальний захист.",
  },
  {
    id: "fluorimeter",
    categoryId: "spectroscopy",
    name: "Флуориметр",
    nameEn: "Fluorimeter / Spectrofluorometer",
    emoji: "🌈",
    description: "Вимірює флуоресценцію зразків для кількісного аналізу та кінетичних досліджень.",
    manufacturers: ["Horiba (FluoroMax)", "Edinburgh Instruments", "Cary Eclipse (Agilent)", "Shimadzu"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Ex діапазон": "220–800 нм", "Em діапазон": "250–900 нм", "Чутливість": "нМ рівень" },
  },
  {
    id: "luminometer",
    categoryId: "spectroscopy",
    name: "Люмінометр",
    nameEn: "Luminometer / Plate Reader",
    emoji: "🌈",
    description: "Вимірювання хемілюмінесценції та біолюмінесценції (ліцефераза, ELISA).",
    manufacturers: ["Berthold Technologies", "Promega (GloMax)", "BMG Labtech (CLARIOstar)", "BioTek"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Чутливість": "до 10⁻¹⁸ моль", "Формат": "96 / 384-лунковий планшет" },
  },
  {
    id: "mass_spectrometer",
    categoryId: "spectroscopy",
    name: "Мас-спектрометр",
    nameEn: "Mass Spectrometer (LC-MS/GC-MS)",
    emoji: "🌈",
    description: "Ідентифікація та кількісний аналіз молекул за масою. Поєднується з ГХ або РХ.",
    manufacturers: ["Waters (Xevo)", "Thermo Fisher (Orbitrap)", "Agilent (Q-TOF)", "Bruker (QTOF)"],
    calibrationDays: 180,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 2,
    specs: { "Тип аналізатора": "Q, TOF, Orbitrap, Ion Trap", "Роздільна здатність": "1000–500 000 FWHM" },
  },

  // ── ХРОМАТОГРАФІЯ ─────────────────────────────────────────────────────────────
  {
    id: "hplc",
    categoryId: "chromatography",
    name: "Рідинний хроматограф (ВЕРХ/HPLC)",
    nameEn: "High-Performance Liquid Chromatograph",
    emoji: "📈",
    description: "Розділення, ідентифікація та кількісне визначення компонентів рідких сумішей.",
    manufacturers: ["Agilent (1260/1290)", "Waters (Alliance, Arc)", "Shimadzu (Nexera)", "Thermo Fisher"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 2,
    specs: { "Тиск": "до 1300 бар (UPLC)", "Детектори": "UV/DAD, RI, FLD, MS", "Колонки": "RP, NP, Ion, Size" },
  },
  {
    id: "gc",
    categoryId: "chromatography",
    name: "Газовий хроматограф (ГХ)",
    nameEn: "Gas Chromatograph (GC/GC-MS)",
    emoji: "📈",
    description: "Аналіз летких сполук. Застосовується в екології, фармації, харчовій промисловості.",
    manufacturers: ["Agilent (7890B)", "Thermo Fisher (Trace 1310)", "Shimadzu (GC-2030)", "PerkinElmer"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 2,
    specs: { "Детектори": "FID, TCD, ECD, NPD, MS", "Температура": "до 450°C", "Газ-носій": "He, N₂, H₂" },
    usageNotes: "Вимагає газових балонів і відповідного регулятора тиску.",
  },
  {
    id: "ion_chromatograph",
    categoryId: "chromatography",
    name: "Іонний хроматограф",
    nameEn: "Ion Chromatograph (IC)",
    emoji: "📈",
    description: "Визначення аніонів та катіонів у водних розчинах.",
    manufacturers: ["Thermo Fisher (Dionex)", "Metrohm", "Shimadzu", "Waters"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Аніони": "F⁻, Cl⁻, NO₃⁻, SO₄²⁻...", "Детектор": "Кондуктометрія" },
  },
  {
    id: "fplc",
    categoryId: "chromatography",
    name: "Рідинна хроматографія (FPLC/ÄKTA)",
    nameEn: "Fast Protein LC / ÄKTA",
    emoji: "📈",
    description: "Очищення білків та нуклеїнових кислот методами іонообміну, афінності, ГФ.",
    manufacturers: ["Cytiva (ÄKTA pure, Explorer)", "Bio-Rad (NGC)", "BioLogic"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: false,
    bslMax: 2,
    specs: { "Тиск": "до 3 МПа", "Детектор": "UV 280 нм / провідність", "Об'єм фракцій": "0.1–100 мл" },
  },
  {
    id: "capillary_electrophoresis",
    categoryId: "chromatography",
    name: "Капілярний електрофорез",
    nameEn: "Capillary Electrophoresis (CE)",
    emoji: "📈",
    description: "Розділення іонів та молекул у тонкому капілярі під впливом електричного поля.",
    manufacturers: ["Agilent (7100)", "Beckman Coulter (PA 800)", "Thermo Fisher"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Напруга": "до 30 кВ", "Режими": "CE, CEC, CGE, MEKC" },
  },

  // ── МОЛЕКУЛЯРНА БІОЛОГІЯ ─────────────────────────────────────────────────────
  {
    id: "pcr_thermocycler",
    categoryId: "molecular_bio",
    name: "ПЛР термоциклер",
    nameEn: "PCR Thermocycler",
    emoji: "🧬",
    description: "Ампліфікація ДНК методом полімеразної ланцюгової реакції.",
    manufacturers: ["Bio-Rad (C1000)", "Thermo Fisher (ProFlex)", "Eppendorf (Mastercycler)", "Applied Biosystems"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Блок": "96 / 384 лунки", "Швидкість нагрів": "до 6°C/с", "Точність температури": "±0.25°C" },
  },
  {
    id: "real_time_pcr",
    categoryId: "molecular_bio",
    name: "Кількісна ПЛР в реальному часі (qPCR)",
    nameEn: "Real-Time PCR / qPCR",
    emoji: "🧬",
    description: "Кількісний аналіз рівня експресії генів, виявлення патогенів.",
    manufacturers: ["Thermo Fisher (QuantStudio)", "Bio-Rad (CFX)", "Roche (LightCycler)", "Applied Biosystems"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Канали": "4–6 флуоресцентних каналів", "Блок": "96 / 384 лунки", "ДОВ": "до 100 Е", "Метод": "SYBR Green, TaqMan" },
  },
  {
    id: "ddpcr",
    categoryId: "molecular_bio",
    name: "Цифровий крапельний ПЛР (ddPCR)",
    nameEn: "Droplet Digital PCR (ddPCR)",
    emoji: "🧬",
    description: "Абсолютна кількісна оцінка ДНК/РНК без стандартних кривих.",
    manufacturers: ["Bio-Rad (QX200)", "Thermo Fisher (QuantStudio 3D)"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Краплі": "~20 000 на реакцію", "Чутливість": "до 1 молекули/реакцію" },
  },
  {
    id: "horizontal_electrophoresis",
    categoryId: "molecular_bio",
    name: "Горизонтальний електрофорез",
    nameEn: "Horizontal Gel Electrophoresis (agarose)",
    emoji: "🧬",
    description: "Розділення ДНК та РНК в агарозному гелі.",
    manufacturers: ["Bio-Rad (Sub-Cell GT)", "Thermo Fisher (Owl)", "Cleaver Scientific"],
    calibrationDays: 0,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Напруга": "до 250 В", "Гель": "0.5–3% агароза", "Формат": "7×10 / 15×25 см" },
  },
  {
    id: "vertical_electrophoresis",
    categoryId: "molecular_bio",
    name: "Вертикальний електрофорез (SDS-PAGE)",
    nameEn: "Vertical Gel Electrophoresis (PAGE)",
    emoji: "🧬",
    description: "Розділення білків за молекулярною масою; вестерн-блот.",
    manufacturers: ["Bio-Rad (Mini-PROTEAN)", "Thermo Fisher (Bolt/NuPAGE)", "Invitrogen", "Hoefer"],
    calibrationDays: 0,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Напруга": "до 300 В", "Гель": "8–20% поліакриламід", "Формат": "Mini (8×8 см) / Midi" },
  },
  {
    id: "gel_doc",
    categoryId: "molecular_bio",
    name: "Гель-документаційна система",
    nameEn: "Gel Documentation System",
    emoji: "🧬",
    description: "Зйомка та аналіз гелів після електрофорезу. УФ або білого світла.",
    manufacturers: ["Bio-Rad (ChemiDoc)", "Syngene (G:BOX)", "Analytik Jena (UVP)", "Li-Cor"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Камера": "≥12 МП CCD", "Освітлення": "UV 302 нм / Epi-White", "Аналіз": "Кількісна денситометрія" },
  },
  {
    id: "sequencer",
    categoryId: "molecular_bio",
    name: "ДНК секвенатор",
    nameEn: "DNA Sequencer (Sanger / NGS)",
    emoji: "🧬",
    description: "Sanger-секвенування (капілярний) або масивне паралельне (NGS/MPS).",
    manufacturers: ["Applied Biosystems (3130xl, 3500)", "Illumina (MiSeq, NextSeq)", "Oxford Nanopore (MinION)"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 2,
    specs: { "Sanger": "до 1200 п.н., 96 капілярів", "NGS": "Гб–Тб за запуск" },
  },

  // ── ТЕРМІЧНЕ ОБЛАДНАННЯ ───────────────────────────────────────────────────────
  {
    id: "incubator",
    categoryId: "thermal",
    name: "Термостат-інкубатор",
    nameEn: "Incubator / Dry Oven",
    emoji: "🌡️",
    description: "Підтримка сталої температури для культивування мікроорганізмів та зберігання зразків.",
    manufacturers: ["Memmert", "Thermo Fisher", "Binder", "Eppendorf"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон": "5–70°C", "Точність": "±0.1°C", "Об'єм": "30–700 л" },
  },
  {
    id: "co2_incubator",
    categoryId: "thermal",
    name: "CO₂-інкубатор",
    nameEn: "CO₂ Incubator",
    emoji: "🌡️",
    description: "Культивування клітин ссавців з контролем CO₂, вологості та температури.",
    manufacturers: ["Thermo Fisher (Heracell)", "Eppendorf (Galaxy)", "Panasonic (MCO)", "Binder"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: false,
    bslMax: 2,
    specs: { "CO₂ діапазон": "0–20%", "Температура": "37°C (до 55°C)", "Деконтамінація": "Heat/UV/H₂O₂" },
    usageNotes: "Підключення до балону з CO₂. Регулярне дезінфекція внутрішньої камери.",
  },
  {
    id: "shaker_incubator",
    categoryId: "thermal",
    name: "Шейкер-інкубатор",
    nameEn: "Shaking Incubator",
    emoji: "🌡️",
    description: "Культивування мікроорганізмів у рідких середовищах при перемішуванні.",
    manufacturers: ["Infors HT (Minitron)", "Thermo Fisher (Maximal)", "Eppendorf (Innova)", "New Brunswick"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Температура": "RT–60°C", "Швидкість": "25–500 об/хв", "Місткість": "до 12 × 5 л колб" },
  },
  {
    id: "water_bath",
    categoryId: "thermal",
    name: "Водяна баня",
    nameEn: "Water Bath",
    emoji: "🌡️",
    description: "Термостатування реакційних сумішей та відігрівання зразків.",
    manufacturers: ["Memmert (WNB)", "Julabo (TW)", "Grant (OLS)", "Thermo Fisher"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон": "RT+5…100°C", "Точність": "±0.1–0.5°C", "Об'єм": "2–25 л" },
  },
  {
    id: "dry_block",
    categoryId: "thermal",
    name: "Сухий термоблок",
    nameEn: "Dry Block Heater / Thermomixer",
    emoji: "🌡️",
    description: "Нагрів і перемішування мікропробірок без рідкого теплоносія.",
    manufacturers: ["Eppendorf (Thermomixer)", "Thermo Fisher", "Grant", "VWR"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон": "RT…110°C", "Перемішування": "300–1400 об/хв (Thermomixer)" },
  },
  {
    id: "autoclave",
    categoryId: "thermal",
    name: "Автоклав",
    nameEn: "Autoclave / Steam Sterilizer",
    emoji: "♨️",
    description: "Парова стерилізація матеріалів, лабораторного посуду та відходів.",
    manufacturers: ["Tuttnauer", "Getinge", "Melag", "Systec", "Hirayama"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 4,
    specs: { "Температура": "121 / 134°C", "Тиск": "1–2.2 бар", "Об'єм": "18–300 л", "Стандарт": "EN 13060 / EN 285" },
    usageNotes: "Підлягає обов'язковій реєстрації та щорічному технічному огляду (посудина під тиском).",
  },
  {
    id: "lyophilizer",
    categoryId: "thermal",
    name: "Ліофілізатор",
    nameEn: "Freeze Dryer / Lyophilizer",
    emoji: "🌡️",
    description: "Сублімаційне висушування — видалення вологи заморожуванням та зниженим тиском.",
    manufacturers: ["Labconco (FreeZone)", "Martin Christ", "SP Scientific (VirTis)", "Buchi"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Температура полиці": "до -85°C", "Вакуум": "до 0.01 мбар", "Продуктивність": "до 6 л/добу" },
  },
  {
    id: "rotary_evaporator",
    categoryId: "thermal",
    name: "Роторний випарювач",
    nameEn: "Rotary Evaporator",
    emoji: "🌡️",
    description: "Відгонка розчинника при зниженому тиску з одночасним обертанням колби.",
    manufacturers: ["Buchi (R-300)", "IKA (RV)", "Heidolph (Hei-VAP)", "Yamato"],
    calibrationDays: 0,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Температура бані": "20–180°C", "Вакуум": "до 1 мбар", "Колба": "до 20 л" },
  },

  // ── КРІОСХОВИЩЕ ───────────────────────────────────────────────────────────────
  {
    id: "lab_refrigerator",
    categoryId: "cold_storage",
    name: "Лабораторний холодильник (+4°C)",
    nameEn: "Laboratory Refrigerator",
    emoji: "🧊",
    description: "Зберігання реагентів, розчинів, вакцин та тканинних культур.",
    manufacturers: ["Thermo Fisher", "Binder", "Panasonic", "Helmer Scientific"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 4,
    specs: { "Температура": "+2…+8°C", "Об'єм": "100–700 л", "Клас": "Фармацевтичний / Науковий" },
  },
  {
    id: "freezer_minus20",
    categoryId: "cold_storage",
    name: "Морозильна камера (-20°C)",
    nameEn: "Freezer (-20°C)",
    emoji: "🧊",
    description: "Довгострокове зберігання ензимів, антитіл, реагентів.",
    manufacturers: ["Thermo Fisher", "Sanyo/Panasonic", "Liebherr", "So-Low"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 3,
    specs: { "Температура": "-15…-25°C", "Об'єм": "80–800 л" },
  },
  {
    id: "ult_freezer",
    categoryId: "cold_storage",
    name: "Ультранизькотемпературний морозильник (-80°C)",
    nameEn: "Ultra-Low Temperature Freezer (ULT, -80°C)",
    emoji: "🧊",
    description: "Зберігання сироваток, плазми, ДНК, кріоконсервованих клітин.",
    manufacturers: ["Thermo Fisher (Forma)", "Eppendorf (CryoCube)", "Panasonic (MDF)", "So-Low"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 3,
    specs: { "Температура": "до -86°C", "Об'єм": "300–750 л", "Споживання": "10–17 кВт·год/добу" },
    usageNotes: "Резервне живлення (UPS) критичне. Моніторинг температури 24/7.",
  },
  {
    id: "liquid_nitrogen_dewar",
    categoryId: "cold_storage",
    name: "Рідкоазотний дюар",
    nameEn: "Liquid Nitrogen Storage Dewar",
    emoji: "🧊",
    description: "Довгострокове кріозберігання клітин, тканин та генетичного матеріалу (-196°C).",
    manufacturers: ["Taylor-Wharton", "Statebourne Cryogenics", "Chart MVE", "Cryotherm"],
    calibrationDays: 0,
    maintenanceDays: 30,
    requiresCert: true,
    bslMax: 3,
    specs: { "Температура": "-196°C", "Місткість": "30–500 л", "Втрати рідкого N₂": "0.1–1 л/добу" },
    usageNotes: "BSL-сертифікат на роботу з рідким азотом. Захист від задухи (кисневий датчик).",
  },

  // ── ПЕРЕМІШУВАННЯ ─────────────────────────────────────────────────────────────
  {
    id: "magnetic_stirrer",
    categoryId: "mixing",
    name: "Магнітна мішалка з нагріванням",
    nameEn: "Magnetic Stirrer with Heating",
    emoji: "🔄",
    description: "Перемішування та нагрів розчинів за допомогою магнітного ротора.",
    manufacturers: ["IKA (C-MAG)", "Heidolph (MR Hei)", "Thermo Fisher", "Radleys"],
    calibrationDays: 0,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 3,
    specs: { "Нагрів": "до 550°C", "Перемішування": "100–1700 об/хв", "Об'єм": "до 10 л" },
  },
  {
    id: "vortex",
    categoryId: "mixing",
    name: "Вортекс-змішувач",
    nameEn: "Vortex Mixer",
    emoji: "🔄",
    description: "Швидке перемішування рідин у пробірках та планшетах.",
    manufacturers: ["IKA (MS 3)", "Scientific Industries (Vortex-Genie 2)", "Thermo Fisher", "Heidolph"],
    calibrationDays: 0,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 4,
    specs: { "Швидкість": "500–3200 об/хв", "Режим": "Touch / Continuous" },
  },
  {
    id: "orbital_shaker",
    categoryId: "mixing",
    name: "Орбітальний шейкер",
    nameEn: "Orbital / Platform Shaker",
    emoji: "🔄",
    description: "Перемішування великих ємностей, планшетів та Western-блот мембран.",
    manufacturers: ["Thermo Fisher (MaxQ)", "IKA (KS)", "VWR", "Heidolph (Polymax)"],
    calibrationDays: 0,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Швидкість": "15–500 об/хв", "Діаметр орбіти": "10–25 мм", "Навантаження": "до 10 кг" },
  },
  {
    id: "rotor_stator_homogenizer",
    categoryId: "mixing",
    name: "Ротор-статорний гомогенізатор",
    nameEn: "Rotor-Stator Homogenizer",
    emoji: "🔄",
    description: "Механічна гомогенізація тканин, клітин та суспензій.",
    manufacturers: ["IKA (Ultra-Turrax T18/T25)", "Bertin (Precellys)", "Polytron", "OMNI"],
    calibrationDays: 0,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Швидкість": "3 000–24 000 об/хв", "Об'єм": "0.01–2 л" },
  },
  {
    id: "sonicator",
    categoryId: "mixing",
    name: "Ультразвуковий гомогенізатор (Соніфікатор)",
    nameEn: "Ultrasonic Homogenizer / Sonicator",
    emoji: "🔄",
    description: "Лізис клітин, нанодисперсія, деагрегація ультразвуком.",
    manufacturers: ["Branson (SFX)", "Hielscher (UIP)", "Qsonica (Q500)", "Dr. Hielscher"],
    calibrationDays: 0,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Частота": "20–40 кГц", "Потужність": "50–3000 Вт", "Об'єм": "0.5 мл–20 л" },
    usageNotes: "Потребує шумового захисту або бокс. Тактильний захист від нагріву зонду.",
  },

  // ── АНАЛІЗ РОЗЧИНІВ ───────────────────────────────────────────────────────────
  {
    id: "ph_meter",
    categoryId: "solution",
    name: "pH-метр",
    nameEn: "pH Meter",
    emoji: "💧",
    description: "Вимірювання водневого показника розчинів. Лабораторний або портативний.",
    manufacturers: ["Mettler Toledo (FiveEasy)", "Hanna Instruments", "Thermo Fisher (Orion)", "WTW"],
    calibrationDays: 30,
    maintenanceDays: 30,
    requiresCert: false,
    bslMax: 4,
    specs: { "Діапазон": "0–14 pH", "Точність": "±0.01 pH", "Компенсація": "ATC (автоматична)" },
    usageNotes: "Електрод потребує зберігання у буферному/KCl-розчині. Калібрування двоточкове щодня.",
  },
  {
    id: "conductometer",
    categoryId: "solution",
    name: "Кондуктометр",
    nameEn: "Conductivity Meter",
    emoji: "💧",
    description: "Вимірювання електропровідності розчинів; контроль якості дистиляту та деіонізату.",
    manufacturers: ["Mettler Toledo", "Hanna Instruments", "WTW (Cond 7110)", "Thermo Fisher"],
    calibrationDays: 180,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 3,
    specs: { "Діапазон": "0.01 мкСм/см–200 мСм/см", "ATC": "Так" },
  },
  {
    id: "osmometer",
    categoryId: "solution",
    name: "Осмометр",
    nameEn: "Osmometer",
    emoji: "💧",
    description: "Визначення осмолярності розчинів (кріоскопічний або мембранний метод).",
    manufacturers: ["Advanced Instruments (Model 3320)", "Löser", "Knauer", "Fiske"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Метод": "Кріоскопія точки замерзання", "Діапазон": "0–4000 мОсм/кг", "Точність": "±1 мОсм/кг" },
  },
  {
    id: "dls_zeta",
    categoryId: "solution",
    name: "DLS / Зета-потенціал аналізатор",
    nameEn: "Dynamic Light Scattering / Zeta Potential Analyzer",
    emoji: "💧",
    description: "Розмір частинок у суспензіях та зета-потенціал колоїдів (нано до мікро).",
    manufacturers: ["Malvern Panalytical (Zetasizer)", "Beckman Coulter (DelsaMax)", "Anton Paar (Litesizer)"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон розміру": "0.3 нм–10 мкм", "Зета-потенціал": "±500 мВ" },
  },
  {
    id: "elisa_reader",
    categoryId: "solution",
    name: "Мікропланшетний фотометр (ELISA Reader)",
    nameEn: "Microplate Reader",
    emoji: "💧",
    description: "Абсорбція, флуоресценція або люмінесценція у форматі 96/384-лункових планшетів.",
    manufacturers: ["BMG Labtech (CLARIOstar, Omega)", "BioTek (Synergy)", "Molecular Devices (Spectramax)", "Tecan"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Режими": "Abs, FL, Lum, TR-FRET", "Довжина хвилі": "230–1000 нм", "Формат": "6–1536-лунок" },
  },

  // ── ЗАХИСТ ПОВІТРЯ ────────────────────────────────────────────────────────────
  {
    id: "bsc_class2",
    categoryId: "safety_air",
    name: "Ламінарний бокс безпеки II класу A2",
    nameEn: "Biosafety Cabinet Class II Type A2",
    emoji: "🛡️",
    description: "Захист оператора, зразка та довкілля від біологічних аерозолів (BSL-2).",
    manufacturers: ["Thermo Fisher (MSC)", "Esco (Labculture)", "Eppendorf (Safe 2020)", "SKAN"],
    calibrationDays: 365,
    maintenanceDays: 365,
    requiresCert: true,
    bslMax: 2,
    specs: { "HEPA-фільтр": "99.99% (0.3 мкм)", "Надлишковий тиск": "Від'ємний", "NSF/EN": "NSF 49 / EN 12469" },
    usageNotes: "Щорічна перевірка HEPA-фільтра. Обов'язкова сертифікація боксу.",
  },
  {
    id: "bsc_class3",
    categoryId: "safety_air",
    name: "Ламінарний бокс безпеки III класу",
    nameEn: "Biosafety Cabinet Class III (Glove Box)",
    emoji: "🛡️",
    description: "Максимальний захист для роботи з BSL-3/4 патогенами. Повністю закритий гловбокс.",
    manufacturers: ["Baker (SterilGARD III)", "Labconco", "SKAN", "Faster"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 4,
    specs: { "Тиск": "Від'ємний (-0.5 мбар)", "Рукавиці": "Герметичні", "Повітря": "Двократна HEPA-фільтрація" },
  },
  {
    id: "chemical_fume_hood",
    categoryId: "safety_air",
    name: "Хімічна витяжна шафа",
    nameEn: "Chemical Fume Hood",
    emoji: "🛡️",
    description: "Захист оператора від хімічних парів при роботі з леткими та токсичними речовинами.",
    manufacturers: ["Labconco", "Kewaunee", "Erlab", "ESCO"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 3,
    specs: { "Швидкість обличчя": "0.5 м/с", "Ширина": "900–2400 мм", "Стандарт": "EN 14175" },
    usageNotes: "Перевірка потоку повітря щорічно. Електричне підключення вентилятора.",
  },
  {
    id: "laminar_flow_cabinet",
    categoryId: "safety_air",
    name: "Ламінар (чистий бокс)",
    nameEn: "Laminar Flow Cabinet (Clean Bench)",
    emoji: "🛡️",
    description: "Захист зразка від забруднення (стерильна зона), але не захист оператора. Для BSL-1.",
    manufacturers: ["Telstar", "Thermo Fisher", "Labconco", "Esco"],
    calibrationDays: 365,
    maintenanceDays: 365,
    requiresCert: false,
    bslMax: 1,
    specs: { "HEPA-фільтр": "99.99%", "Горизонтальний / Вертикальний": "Обидва типи" },
  },
  {
    id: "isolator",
    categoryId: "safety_air",
    name: "Ізолятор (Гловбокс)",
    nameEn: "Isolator / Glovebox",
    emoji: "🛡️",
    description: "Повністю закрита система для роботи в інертній атмосфері або з токсичними речовинами.",
    manufacturers: ["Jacomex", "MBraun", "Vacuum Atmospheres", "Plas-Labs"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 4,
    specs: { "Атмосфера": "N₂, Ar або повітря", "O₂/H₂O": "<1 ppm (інертні)", "Тиск": "Контрольований" },
  },

  // ── ДОЗУВАННЯ РІДИН ──────────────────────────────────────────────────────────
  {
    id: "pipette_single_channel",
    categoryId: "dispensing",
    name: "Одноканальна механічна піпетка",
    nameEn: "Single-Channel Mechanical Pipette",
    emoji: "💉",
    description: "Точне дозування рідин у мкл-діапазоні. Доступна у чотирьох діапазонах.",
    manufacturers: ["Eppendorf (Research Plus)", "Gilson (PIPETMAN)", "Thermo Fisher (Finnpipette)", "Sartorius (Picus)"],
    calibrationDays: 365,
    maintenanceDays: 365,
    requiresCert: true,
    bslMax: 4,
    specs: { "Діапазони": "0.1–2, 2–20, 20–200, 100–1000 мкл", "Стандарт": "ISO 8655", "CV": "<1%" },
    usageNotes: "Підлягає метрологічній перевірці згідно ISO 8655.",
  },
  {
    id: "pipette_multichannel",
    categoryId: "dispensing",
    name: "Багатоканальна піпетка (8/12-канальна)",
    nameEn: "Multichannel Pipette",
    emoji: "💉",
    description: "Паралельне дозування у 8 або 12 лунок 96-лункового планшету.",
    manufacturers: ["Eppendorf (Research Plus)", "Gilson (PIPETMAN Multi)", "Thermo Fisher", "Sartorius"],
    calibrationDays: 365,
    maintenanceDays: 365,
    requiresCert: true,
    bslMax: 4,
    specs: { "Канали": "8 або 12", "Діапазон": "0.5–300 мкл" },
  },
  {
    id: "electronic_pipette",
    categoryId: "dispensing",
    name: "Електронна піпетка",
    nameEn: "Electronic Pipette",
    emoji: "💉",
    description: "Програмоване дозування з різними режимами: однократне, серійне, змішування.",
    manufacturers: ["Eppendorf (epMotion)", "Thermo Fisher (FAST 384)", "Sartorius (Picus Neo)", "Integra (VIAFLO)"],
    calibrationDays: 365,
    maintenanceDays: 365,
    requiresCert: true,
    bslMax: 4,
    specs: { "Режими": "Стандартний, серійний, зворотній, змішування", "CV": "<0.5%" },
  },
  {
    id: "liquid_handler",
    categoryId: "dispensing",
    name: "Автоматичний дозатор (Liquid Handler)",
    nameEn: "Automated Liquid Handler",
    emoji: "🤖",
    description: "Роботизований дозатор для серійного переносу рідин у мікропланшетах.",
    manufacturers: ["Hamilton (Microlab STAR)", "Tecan (Fluent)", "Beckman Coulter (Biomek)", "Agilent (Bravo)"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 2,
    specs: { "Канали": "8–384", "Об'єм": "0.5 мкл–50 мл", "Платформа": "SBS-сумісна" },
  },
  {
    id: "peristaltic_pump",
    categoryId: "dispensing",
    name: "Перистальтичний насос",
    nameEn: "Peristaltic Pump",
    emoji: "💉",
    description: "Безперервна подача рідин для хроматографії, ферментації та систем промивки.",
    manufacturers: ["Watson Marlow", "Cole-Parmer (Masterflex)", "Ismatec", "Weitzel"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Швидкість потоку": "0.001 мкл/хв–3 л/хв", "Трубки": "Silicone, Pharmed, Tygon" },
  },

  // ── ЕЛЕКТРОХІМІЯ ─────────────────────────────────────────────────────────────
  {
    id: "potentiostat",
    categoryId: "electrochemistry",
    name: "Потенціостат / Гальваностат",
    nameEn: "Potentiostat / Galvanostat",
    emoji: "⚡",
    description: "Електрохімічні дослідження: циклічна вольтамперометрія, хронопотенціометрія, EIS.",
    manufacturers: ["Metrohm Autolab (PGSTAT)", "Bio-Logic (VMP3)", "Gamry (Reference)", "CH Instruments"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Потенціал": "±10 В", "Струм": "від пА до 20 А", "EIS": "Так (10 мкГц–1 МГц)" },
  },
  {
    id: "coulter_counter",
    categoryId: "electrochemistry",
    name: "Лічильник частинок (Coulter Counter)",
    nameEn: "Coulter Counter / Cell Counter",
    emoji: "⚡",
    description: "Підрахунок та визначення розміру частинок/клітин методом витіснення.",
    manufacturers: ["Beckman Coulter (Z2)", "Thermo Fisher (Multisizer)", "Sysmex"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: false,
    bslMax: 2,
    specs: { "Діапазон": "0.4–1200 мкм", "Канали": "до 256" },
  },
  {
    id: "flow_cytometer",
    categoryId: "electrochemistry",
    name: "Проточний цитометр",
    nameEn: "Flow Cytometer",
    emoji: "⚡",
    description: "Багатопараметричний аналіз клітин у суспензії за флуоресценцією та розсіюванням.",
    manufacturers: ["BD Biosciences (FACSAria)", "Beckman Coulter (CytoFLEX)", "Thermo Fisher (Attune)", "Miltenyi (MACSQuant)"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: true,
    bslMax: 2,
    specs: { "Лазери": "до 5 (488, 405, 638, 561, 355 нм)", "Детектори": "до 30 каналів", "Сортування": "FACS (опціонально)" },
  },

  // ── РЕНТГЕН / ЯДЕРНЕ ─────────────────────────────────────────────────────────
  {
    id: "xrd",
    categoryId: "xray_nuclear",
    name: "Рентгенівський дифрактометр (XRD)",
    nameEn: "X-Ray Diffractometer (XRD / PXRD)",
    emoji: "☢️",
    description: "Визначення кристалічної структури, фазовий аналіз порошків та монокристалів.",
    manufacturers: ["Bruker (D8 Advance)", "Rigaku", "Malvern Panalytical (Empyrean)", "Shimadzu"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 1,
    specs: { "Джерело": "Cu Kα (1.5406 Å)", "Детектор": "LYNXEYE / Scintillator", "Кут": "5–90° 2θ" },
    usageNotes: "Ліцензія на джерело іонізуючого випромінювання обов'язкова.",
  },
  {
    id: "xrf",
    categoryId: "xray_nuclear",
    name: "Рентгенофлуоресцентний спектрометр (XRF)",
    nameEn: "X-Ray Fluorescence Spectrometer (XRF)",
    emoji: "☢️",
    description: "Елементний аналіз твердих матеріалів без руйнування зразка.",
    manufacturers: ["Bruker (S1 TITAN)", "Malvern Panalytical (Axios)", "Thermo Fisher (Niton)", "Rigaku"],
    calibrationDays: 365,
    maintenanceDays: 180,
    requiresCert: true,
    bslMax: 1,
    specs: { "Елементи": "F–U (11–92)", "Межа виявлення": "ppm рівень" },
    usageNotes: "Ліцензія на джерело іонізуючого випромінювання.",
  },
  {
    id: "geiger_counter",
    categoryId: "xray_nuclear",
    name: "Радіометр (Лічильник Гейгера)",
    nameEn: "Geiger Counter / Radiation Monitor",
    emoji: "☢️",
    description: "Вимірювання дози та потужності дози α, β, γ-випромінювання.",
    manufacturers: ["Ludlum", "Thermo Fisher (FH-40G)", "Polimaster", "Berthold"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: true,
    bslMax: 4,
    specs: { "Типи": "α, β, γ (X)", "Одиниці": "мкЗв/год, cpm" },
    usageNotes: "Щорічна державна повірка обов'язкова.",
  },

  // ── ЗАГАЛЬНЕ ────────────────────────────────────────────────────────────────
  {
    id: "water_purification",
    categoryId: "general",
    name: "Система отримання надчистої води",
    nameEn: "Ultrapure Water System (Type 1)",
    emoji: "💎",
    description: "Отримання надчистої води (Type I, <0.1 мкСм/см) для ВЕРХ, молекулярної біології, ICP-MS.",
    manufacturers: ["Merck Millipore (Milli-Q)", "Thermo Fisher (Barnstead)", "ELGA (PURELAB)", "Evoqua"],
    calibrationDays: 365,
    maintenanceDays: 90,
    requiresCert: false,
    bslMax: 2,
    specs: { "Питомий опір": "18.2 МОм·см", "TOC": "<5 ppb", "Тип I/II/III": "Залежно від системи" },
  },
  {
    id: "vacuum_pump",
    categoryId: "general",
    name: "Вакуумний насос",
    nameEn: "Vacuum Pump",
    emoji: "🔧",
    description: "Для ротаційних випарювачів, вакуумної фільтрації, ліофілізаторів та ін.",
    manufacturers: ["Vacuubrand (PC 3001)", "Welch", "Edwards", "Pfeiffer"],
    calibrationDays: 0,
    maintenanceDays: 180,
    requiresCert: false,
    bslMax: 2,
    specs: { "Мінімальний тиск": "0.1–2 мбар", "Продуктивність": "2–100 м³/год" },
  },
  {
    id: "digital_micrometer",
    categoryId: "general",
    name: "Мікрометр / Штангенциркуль цифровий",
    nameEn: "Digital Micrometer / Caliper",
    emoji: "📐",
    description: "Точне вимірювання лінійних розмірів зразків та деталей.",
    manufacturers: ["Mitutoyo", "Mahr", "Starrett", "Insize"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: true,
    bslMax: 1,
    specs: { "Точність": "±0.001 мм (мікрометр)", "Діапазон": "0–25 / 0–150 мм" },
  },
  {
    id: "cell_counter",
    categoryId: "general",
    name: "Автоматичний лічильник клітин",
    nameEn: "Automated Cell Counter",
    emoji: "🧮",
    description: "Підрахунок клітин та визначення їх viability (трипановий синій або флуоресценція).",
    manufacturers: ["Bio-Rad (TC20)", "Thermo Fisher (Countess 3)", "Nexcelom (Celigo)", "Chemometec (NucleoCounter)"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Метод": "Трипановий синій / AO-PI", "Час аналізу": "<30 с" },
  },
  {
    id: "nanodrop",
    categoryId: "general",
    name: "NanoDrop / Мікрооб'ємний спектрофотометр",
    nameEn: "Microvolume UV-Vis Spectrophotometer (NanoDrop)",
    emoji: "🔬",
    description: "Вимірювання концентрації ДНК, РНК та білків у 1–2 мкл без кювети.",
    manufacturers: ["Thermo Fisher (NanoDrop One)", "DeNovix (DS-11)", "Biochrom (Libra)"],
    calibrationDays: 365,
    maintenanceDays: 0,
    requiresCert: false,
    bslMax: 2,
    specs: { "Об'єм зразка": "0.5–2 мкл", "Діапазон": "2–15 000 нг/мкл (dsDNA)", "Точність": "±2%" },
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
export function getCatalogCategory(id: string) {
  return CATALOG_CATEGORIES.find(c => c.id === id);
}

export function getItemsByCategory(categoryId: string) {
  if (categoryId === "all") return CATALOG_ITEMS;
  return CATALOG_ITEMS.filter(i => i.categoryId === categoryId);
}

export function searchCatalog(query: string): CatalogItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return CATALOG_ITEMS;
  return CATALOG_ITEMS.filter(i =>
    i.name.toLowerCase().includes(q) ||
    i.nameEn.toLowerCase().includes(q) ||
    i.description.toLowerCase().includes(q) ||
    i.manufacturers.some(m => m.toLowerCase().includes(q))
  );
}

export function calIntervalLabel(days: number): string {
  if (days === 0) return "Не потребує";
  if (days <= 30)  return `${days} днів`;
  if (days <= 90)  return `${days / 30} міс.`;
  if (days === 365) return "1 рік";
  return `${days} днів`;
}
