// ─── Reagent Catalog — classified chemical & consumable reference ──────────────

import type { LabInventoryCategory, LabHazardClass } from "./mobile-store";

export type ReagentCatalogCategory = {
  id: string;
  label: string;
  labelShort: string;
  emoji: string;
  color: string;
};

export type ReagentCatalogItem = {
  id: string;
  categoryId: string;
  invCategory: LabInventoryCategory;
  name: string;
  nameEn: string;
  emoji: string;
  casNumber?: string;
  description: string;
  hazardClass: LabHazardClass;
  storageConditions: string;
  defaultUnit: string;
  manufacturers: string[];
  notes?: string;
};

// ─── Categories ───────────────────────────────────────────────────────────────
export const REAGENT_CATEGORIES: ReagentCatalogCategory[] = [
  { id: "buffers",      label: "Буфери і розчини",      labelShort: "Буфери",    emoji: "💧", color: "#0369a1" },
  { id: "detergents",   label: "Детергенти та ден-ти",  labelShort: "Детерг.",   emoji: "🫧", color: "#7c3aed" },
  { id: "mol_bio",      label: "Молекулярна біологія",  labelShort: "Мол. біол.",emoji: "🧬", color: "#0891b2" },
  { id: "cell_culture", label: "Клітинні культури",     labelShort: "Культури",  emoji: "🧫", color: "#059669" },
  { id: "acids_bases",  label: "Кислоти та луги",        labelShort: "Кислоти",   emoji: "⚗️", color: "#dc2626" },
  { id: "solvents",     label: "Органічні розчинники",  labelShort: "Розчинники",emoji: "🧴", color: "#d97706" },
  { id: "dyes",         label: "Барвники та індикатори", labelShort: "Барвники",  emoji: "🎨", color: "#be185d" },
  { id: "antibiotics",  label: "Антибіотики",            labelShort: "Антибіот.", emoji: "💊", color: "#16a34a" },
  { id: "media",        label: "Поживні середовища",    labelShort: "Середовища",emoji: "🧫", color: "#92400e" },
  { id: "standards",    label: "Стандарти та маркери",  labelShort: "Стандарти", emoji: "📊", color: "#0f766e" },
  { id: "consumables",  label: "Витратні матеріали",    labelShort: "Витратні",  emoji: "📦", color: "#64748b" },
  { id: "salts",        label: "Солі та реактиви",       labelShort: "Солі",      emoji: "🧪", color: "#b45309" },
];

// ─── Catalog items ────────────────────────────────────────────────────────────
export const REAGENT_ITEMS: ReagentCatalogItem[] = [

  // ── БУФЕРИ ──────────────────────────────────────────────────────────────────
  {
    id: "pbs",
    categoryId: "buffers",
    invCategory: "reagent",
    name: "PBS (Фосфатно-сольовий буфер)",
    nameEn: "Phosphate Buffered Saline (PBS), pH 7.4",
    emoji: "💧",
    description: "Ізотонічний буфер для промивки клітин, розведення антитіл та розчинів для ін'єкцій.",
    hazardClass: "none",
    storageConditions: "RT, стерильний — +4°C",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Thermo Fisher", "Gibco", "Merck"],
    notes: "pH 7.4 (±0.05). Стерилізація фільтруванням 0.22 мкм або автоклавуванням.",
  },
  {
    id: "tbs",
    categoryId: "buffers",
    invCategory: "reagent",
    name: "TBS (Тріс-сольовий буфер)",
    nameEn: "Tris-Buffered Saline (TBS), pH 7.5",
    emoji: "💧",
    description: "Альтернативний PBS, сумісніший з деякими детекційними системами (без фосфату).",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Bio-Rad", "Thermo Fisher"],
  },
  {
    id: "hepes",
    categoryId: "buffers",
    invCategory: "reagent",
    name: "HEPES буфер",
    nameEn: "HEPES (4-(2-hydroxyethyl)-1-piperazineethanesulfonic acid)",
    emoji: "💧",
    casNumber: "7365-45-9",
    description: "Цитосумісний Good-буфер для клітинних культур і біохімічних досліджень. pKa 7.55.",
    hazardClass: "none",
    storageConditions: "RT, захищати від вологи",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Thermo Fisher", "AppliChem"],
    notes: "Концентрований розчин 1М зберігається при +4°C до 1 року.",
  },
  {
    id: "tris_base",
    categoryId: "buffers",
    invCategory: "reagent",
    name: "Tris (трисамінометан)",
    nameEn: "Tris base / Tris(hydroxymethyl)aminomethane",
    emoji: "💧",
    casNumber: "77-86-1",
    description: "Базовий компонент більшості лабораторних буферів. Широкий діапазон pH 7–9.",
    hazardClass: "none",
    storageConditions: "RT, суха темна шафа",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem", "Invitrogen"],
  },
  {
    id: "edta",
    categoryId: "buffers",
    invCategory: "reagent",
    name: "ЕДТА (Етилендіамінтетраоцтова кислота)",
    nameEn: "EDTA disodium salt dihydrate",
    emoji: "💧",
    casNumber: "6381-92-6",
    description: "Хелатор двовалентних катіонів (Ca²⁺, Mg²⁺). Використовується у ПЛР, клітинній біології.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
    notes: "Розчиняється при pH ~8 (підтитрувати NaOH). 0.5М розчин — стандарт.",
  },
  {
    id: "tae_buffer",
    categoryId: "buffers",
    invCategory: "reagent",
    name: "TAE буфер (50×)",
    nameEn: "Tris-Acetate-EDTA buffer, 50× concentrate",
    emoji: "💧",
    description: "Електрофорезний буфер для агарозних гелів ДНК. Краще для великих фрагментів.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Bio-Rad", "Thermo Fisher"],
  },
  {
    id: "tbe_buffer",
    categoryId: "buffers",
    invCategory: "reagent",
    name: "TBE буфер (10×)",
    nameEn: "Tris-Borate-EDTA buffer, 10× concentrate",
    emoji: "💧",
    description: "Електрофорезний буфер для агарозних і ПААГ-гелів. Кращий для малих фрагментів.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Bio-Rad", "Thermo Fisher"],
  },
  {
    id: "glycine",
    categoryId: "buffers",
    invCategory: "reagent",
    name: "Гліцин",
    nameEn: "Glycine",
    emoji: "💧",
    casNumber: "56-40-6",
    description: "Компонент буферів для SDS-PAGE (running buffer), блокування та вестерн-блоту.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Bio-Rad"],
  },

  // ── ДЕТЕРГЕНТИ ───────────────────────────────────────────────────────────────
  {
    id: "sds",
    categoryId: "detergents",
    invCategory: "reagent",
    name: "SDS (Лаурилсульфат натрію)",
    nameEn: "Sodium Dodecyl Sulfate (SDS)",
    emoji: "🫧",
    casNumber: "151-21-3",
    description: "Аніонний детергент для денатурування білків у SDS-PAGE та лізису клітин.",
    hazardClass: "corrosive",
    storageConditions: "RT, захищати від вологи",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Bio-Rad", "AppliChem"],
    notes: "10% розчин — стандарт для SDS-PAGE. Подразнює шкіру та очі.",
  },
  {
    id: "triton_x100",
    categoryId: "detergents",
    invCategory: "reagent",
    name: "Тритон X-100",
    nameEn: "Triton X-100 (polyethylene glycol p-(1,1,3,3-tetramethylbutyl)-phenyl ether)",
    emoji: "🫧",
    casNumber: "9002-93-1",
    description: "Неіонний детергент для пермеабілізації клітин, солюбілізації мембранних білків.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "Thermo Fisher"],
    notes: "10% розчин — робочий. Пінить при перемішуванні.",
  },
  {
    id: "tween20",
    categoryId: "detergents",
    invCategory: "reagent",
    name: "Твін-20 (Полісорбат 20)",
    nameEn: "Tween-20 / Polysorbate 20",
    emoji: "🫧",
    casNumber: "9005-64-5",
    description: "Неіонний детергент для блокування в ELISA та вестерн-блоті (TBST/PBST).",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem"],
    notes: "0.05–0.1% у блокувальному буфері. Знижує неспецифічне зв'язування.",
  },
  {
    id: "bme",
    categoryId: "detergents",
    invCategory: "reagent",
    name: "β-Меркаптоетанол (BME)",
    nameEn: "β-Mercaptoethanol (2-Mercaptoethanol)",
    emoji: "🫧",
    casNumber: "60-24-2",
    description: "Редукуючий агент для розривання дисульфідних зв'язків у білках. Компонент SDS-PAGE зразкового буфера.",
    hazardClass: "toxic",
    storageConditions: "+4°C, витяжна шафа",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Merck", "AppliChem"],
    notes: "Гострий запах. Використовувати лише у витяжній шафі. Токсичний при вдиханні.",
  },
  {
    id: "dtt",
    categoryId: "detergents",
    invCategory: "reagent",
    name: "DTT (Дітіотреїтол)",
    nameEn: "Dithiothreitol (DTT) / Clelands reagent",
    emoji: "🫧",
    casNumber: "3483-12-3",
    description: "Редукуючий агент, альтернатива BME. Для захисту SH-груп білків. Нижча леткість.",
    hazardClass: "none",
    storageConditions: "-20°C",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem", "Thermo Fisher"],
    notes: "1М розчин аліквотами по 1 мл при -20°C. Термолабільний.",
  },
  {
    id: "urea",
    categoryId: "detergents",
    invCategory: "reagent",
    name: "Сечовина (Карбамід)",
    nameEn: "Urea",
    emoji: "🫧",
    casNumber: "57-13-6",
    description: "Хаотропний денатурант для розгортання білків. Застосовується при рефолдингу та 2D-PAGE.",
    hazardClass: "none",
    storageConditions: "RT, суха шафа",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem"],
    notes: "8М — денатурувальні умови. Свіжоприготований розчин для оптимальних результатів.",
  },
  {
    id: "pmsf",
    categoryId: "detergents",
    invCategory: "reagent",
    name: "PMSF (Фенілметилсульфонілфторид)",
    nameEn: "Phenylmethylsulfonyl fluoride (PMSF)",
    emoji: "🫧",
    casNumber: "329-98-6",
    description: "Інгібітор серинових протеаз. Додається до лізисних буферів для збереження білків.",
    hazardClass: "toxic",
    storageConditions: "-20°C, суха шафа",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Thermo Fisher"],
    notes: "100 мМ у ізопропанолі = робочий стоковий розчин. T½ в воді ~35 хв при pH 7.",
  },
  {
    id: "np40",
    categoryId: "detergents",
    invCategory: "reagent",
    name: "NP-40 (Nonidet P-40)",
    nameEn: "NP-40 / Nonidet P-40 / IGEPAL CA-630",
    emoji: "🫧",
    description: "Неіонний детергент для м'якого лізису клітин зі збереженням ядер.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem"],
  },

  // ── МОЛЕКУЛЯРНА БІОЛОГІЯ ─────────────────────────────────────────────────────
  {
    id: "dntp_mix",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "dNTP суміш (10 мМ кожен)",
    nameEn: "dNTP Mix (dATP, dCTP, dGTP, dTTP, 10 mM each)",
    emoji: "🧬",
    description: "Нуклеотидна суміш для ПЛР та синтезу кДНК. Стандарт молекулярної біології.",
    hazardClass: "none",
    storageConditions: "-20°C",
    defaultUnit: "мкл",
    manufacturers: ["Thermo Fisher", "New England Biolabs", "Promega", "Roche"],
    notes: "Аліквотувати! Уникати повторного заморожування–відтавання.",
  },
  {
    id: "etbr",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "Етидію бромід (EtBr)",
    nameEn: "Ethidium Bromide (EtBr)",
    emoji: "🧬",
    casNumber: "1239-45-8",
    description: "Інтеркалюючий барвник для візуалізації ДНК в агарозних гелях під УФ. Мутаген.",
    hazardClass: "toxic",
    storageConditions: "RT, темне місце, спец. зберігання",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "Thermo Fisher"],
    notes: "МУТАГЕН. Окремі лабораторні рукавиці, поверхні, відходи. Рекомендується замінити GelRed/GelGreen.",
  },
  {
    id: "gelred",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "GelRed™ (замінник EtBr)",
    nameEn: "GelRed Nucleic Acid Stain",
    emoji: "🧬",
    description: "Безпечний замінник EtBr для фарбування ДНК. Не проникає через клітинну мембрану.",
    hazardClass: "none",
    storageConditions: "RT, темне місце",
    defaultUnit: "мкл",
    manufacturers: ["Biotium", "Sigma-Aldrich"],
  },
  {
    id: "agarose",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "Агароза (стандартна)",
    nameEn: "Agarose, standard grade",
    emoji: "🧬",
    description: "Для приготування агарозних гелів для електрофорезу ДНК. 0.5–3%.",
    hazardClass: "none",
    storageConditions: "RT, суха шафа",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Lonza", "Bio-Rad"],
  },
  {
    id: "acrylamide_30",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "Акриламід/Біс-акриламід 30% (29:1)",
    nameEn: "Acrylamide/Bisacrylamide Solution 30%, 29:1",
    emoji: "🧬",
    casNumber: "79-06-1",
    description: "Для приготування поліакриламідних гелів (SDS-PAGE, нативний PAGE).",
    hazardClass: "toxic",
    storageConditions: "+4°C, темне місце",
    defaultUnit: "мл",
    manufacturers: ["Bio-Rad", "Sigma-Aldrich", "Roth"],
    notes: "Нейротоксин у мономерній формі. Поліакриламід — нетоксичний.",
  },
  {
    id: "temed",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "TEMED (тетраметилетилендіамін)",
    nameEn: "N,N,N',N'-Tetramethylethylenediamine (TEMED)",
    emoji: "🧬",
    casNumber: "110-18-9",
    description: "Каталізатор полімеризації акриламіду разом з APS. Компонент ПААГ-гелів.",
    hazardClass: "flammable",
    storageConditions: "+4°C",
    defaultUnit: "мл",
    manufacturers: ["Bio-Rad", "Sigma-Aldrich", "Roth"],
  },
  {
    id: "aps",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "APS (Пероксодисульфат амонію)",
    nameEn: "Ammonium Persulfate (APS)",
    emoji: "🧬",
    casNumber: "7727-54-0",
    description: "Ініціатор полімеризації поліакриламіду. 10% розчин — стандарт.",
    hazardClass: "oxidizing",
    storageConditions: "RT (порошок), +4°C (10% розчин, до 2 тижнів)",
    defaultUnit: "г",
    manufacturers: ["Bio-Rad", "Sigma-Aldrich", "Roth"],
    notes: "Свіжоприготований 10% розчин — кращий результат полімеризації.",
  },
  {
    id: "glycerol",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "Гліцерол (Гліцерин)",
    nameEn: "Glycerol (Glycerin)",
    emoji: "🧬",
    casNumber: "56-81-5",
    description: "Кріопротектор для зберігання бактерій (-80°C). Компонент зразкового буфера ПЛР.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem"],
  },
  {
    id: "loading_dye",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "Loading Dye ДНК (6×)",
    nameEn: "DNA Loading Dye 6×",
    emoji: "🧬",
    description: "Барвний буфер для нанесення ДНК на агарозний гель. Містить бромфеноловий синій.",
    hazardClass: "none",
    storageConditions: "RT або +4°C",
    defaultUnit: "мкл",
    manufacturers: ["Thermo Fisher", "New England Biolabs", "Sigma-Aldrich"],
  },
  {
    id: "protein_loading_buffer",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "Laemmli Sample Buffer (4×)",
    nameEn: "Protein Sample Buffer / Laemmli 4× (SDS-PAGE)",
    emoji: "🧬",
    description: "Зразковий буфер для SDS-PAGE. Містить SDS, гліцерол, BME, бромфеноловий синій.",
    hazardClass: "toxic",
    storageConditions: "-20°C (аліквоти)",
    defaultUnit: "мкл",
    manufacturers: ["Bio-Rad", "Sigma-Aldrich", "Thermo Fisher"],
  },
  {
    id: "blocking_milk",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "Знежирене молоко (блокування)",
    nameEn: "Non-fat dried milk (blocking agent)",
    emoji: "🧬",
    description: "Для блокування неспецифічного зв'язування в вестерн-блоті. 5% у TBST.",
    hazardClass: "none",
    storageConditions: "RT, суха шафа",
    defaultUnit: "г",
    manufacturers: ["Bio-Rad (Blotting Grade Blocker)", "AppliChem", "Sigma-Aldrich"],
  },
  {
    id: "bsa",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "БСА (Бичачий сироватковий альбумін)",
    nameEn: "BSA — Bovine Serum Albumin",
    emoji: "🧬",
    casNumber: "9048-46-8",
    description: "Блокуючий агент для ELISA, IHC, IP; стабілізатор ферментів; стандарт для BCA.",
    hazardClass: "none",
    storageConditions: "+4°C",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich (A9418)", "Roth", "Thermo Fisher"],
    notes: "Фракція V — для більшості застосувань. Acetylated BSA — для деяких ензимів.",
  },
  {
    id: "rnase_a",
    categoryId: "mol_bio",
    invCategory: "reagent",
    name: "РНКаза A",
    nameEn: "RNase A (Ribonuclease A)",
    emoji: "🧬",
    description: "Ензим для деградації РНК при виділенні плазмідної ДНК. Надзвичайно стабільний.",
    hazardClass: "none",
    storageConditions: "-20°C",
    defaultUnit: "мкл",
    manufacturers: ["Thermo Fisher", "Roche", "New England Biolabs"],
    notes: "Для інактивації — кип'ятити 15 хв. Забруднює ДНК-препарати.",
  },

  // ── КЛІТИННІ КУЛЬТУРИ ─────────────────────────────────────────────────────────
  {
    id: "dmem",
    categoryId: "cell_culture",
    invCategory: "reagent",
    name: "DMEM (Поживне середовище Дульбекко)",
    nameEn: "DMEM — Dulbecco's Modified Eagle's Medium",
    emoji: "🧫",
    description: "Базове середовище для культивування більшості клітинних ліній ссавців.",
    hazardClass: "none",
    storageConditions: "+4°C, захищати від світла",
    defaultUnit: "мл",
    manufacturers: ["Gibco/Thermo Fisher", "Sigma-Aldrich", "Lonza", "PAN-Biotech"],
    notes: "Зберігати захищеним від світла. Відкриті пляшки — до 1 місяця при +4°C.",
  },
  {
    id: "rpmi",
    categoryId: "cell_culture",
    invCategory: "reagent",
    name: "RPMI-1640",
    nameEn: "RPMI-1640 Medium",
    emoji: "🧫",
    description: "Середовище для лімфоцитів, імунних клітин та гематологічних клітинних ліній.",
    hazardClass: "none",
    storageConditions: "+4°C, захищати від світла",
    defaultUnit: "мл",
    manufacturers: ["Gibco/Thermo Fisher", "Sigma-Aldrich", "Lonza"],
  },
  {
    id: "fbs",
    categoryId: "cell_culture",
    invCategory: "reagent",
    name: "FBS (Ембріональна бичача сироватка)",
    nameEn: "FBS — Fetal Bovine Serum",
    emoji: "🧫",
    description: "Джерело ростових факторів та поживних речовин для культур клітин (5–20%).",
    hazardClass: "none",
    storageConditions: "-20°C (зберігання), +4°C (після розморожування)",
    defaultUnit: "мл",
    manufacturers: ["Gibco/Thermo Fisher", "Sigma-Aldrich", "Capricorn Scientific"],
    notes: "Інактивувати при 56°C, 30 хв. Аліквотувати по 50 мл.",
  },
  {
    id: "pen_strep",
    categoryId: "cell_culture",
    invCategory: "reagent",
    name: "Пеніцилін-Стрептоміцин (100×)",
    nameEn: "Penicillin-Streptomycin Solution 100×",
    emoji: "🧫",
    description: "Антибактеріальний коктейль для попередження контамінації клітинних культур.",
    hazardClass: "none",
    storageConditions: "-20°C",
    defaultUnit: "мл",
    manufacturers: ["Gibco/Thermo Fisher", "Sigma-Aldrich", "Lonza"],
    notes: "Робоча концентрація: 1× (100 ОД/мл пеніциліну + 100 мкг/мл стрептоміцину).",
  },
  {
    id: "l_glutamine",
    categoryId: "cell_culture",
    invCategory: "reagent",
    name: "L-Глутамін (200 мМ)",
    nameEn: "L-Glutamine 200 mM (100×)",
    emoji: "🧫",
    casNumber: "56-85-9",
    description: "Необхідна амінокислота для росту клітин. Нестабільна при +4°C (>3 тижні).",
    hazardClass: "none",
    storageConditions: "-20°C",
    defaultUnit: "мл",
    manufacturers: ["Gibco/Thermo Fisher", "Sigma-Aldrich", "Lonza"],
    notes: "Додавати свіжий L-Gln до середовища щомісяця. GlutaMAX — стабільна альтернатива.",
  },
  {
    id: "trypsin_edta",
    categoryId: "cell_culture",
    invCategory: "reagent",
    name: "Трипсин-EDTA (0.25%)",
    nameEn: "Trypsin-EDTA 0.25%",
    emoji: "🧫",
    description: "Для відокремлення адгерентних клітин від поверхні культурального флакону.",
    hazardClass: "none",
    storageConditions: "-20°C (зберігання), +4°C (в роботі)",
    defaultUnit: "мл",
    manufacturers: ["Gibco/Thermo Fisher", "Sigma-Aldrich"],
    notes: "Нейтралізувати FBS-вмісним середовищем після трипсинізації.",
  },
  {
    id: "dmso_cryogenic",
    categoryId: "cell_culture",
    invCategory: "reagent",
    name: "DMSO (кріопротектор, клітинний)",
    nameEn: "Dimethyl Sulfoxide (DMSO), cell culture grade",
    emoji: "🧫",
    casNumber: "67-68-5",
    description: "Кріопротектор для заморожування клітин. 10% у FBS або CryoStor.",
    hazardClass: "none",
    storageConditions: "RT (темна шафа)",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich (Hybri-Max)", "AppliChem", "Thermo Fisher"],
    notes: "Виробляє тепло при змішуванні з водою. Швидко проникає через шкіру — рукавиці.",
  },

  // ── КИСЛОТИ ТА ЛУГИ ───────────────────────────────────────────────────────────
  {
    id: "hcl_37",
    categoryId: "acids_bases",
    invCategory: "reagent",
    name: "Соляна кислота 37% (Хлороводнева)",
    nameEn: "Hydrochloric Acid 37% (Fuming)",
    emoji: "⚗️",
    casNumber: "7647-01-0",
    description: "Концентрована кислота. Для кислотного гідролізу, титрування, приготування розчинів.",
    hazardClass: "corrosive",
    storageConditions: "Витяжна шафа, кислотна шафа, окремо від лугів",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Merck", "VWR", "Roth"],
    notes: "Леткий HCl-газ. Зберігати в кислотній шафі з вентиляцією.",
  },
  {
    id: "h2so4_98",
    categoryId: "acids_bases",
    invCategory: "reagent",
    name: "Сірчана кислота 98% (концентрована)",
    nameEn: "Sulfuric Acid 98% (conc.)",
    emoji: "⚗️",
    casNumber: "7664-93-9",
    description: "Сильна кислота-дегідратант. Для аналізу, синтезу, підкислення та мінералізації.",
    hazardClass: "corrosive",
    storageConditions: "Кислотна шафа, окремо від органіки та лугів",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Merck", "Roth", "VWR"],
    notes: "Сильний екзотермічний ефект при розведенні. Завжди додавати кислоту до ВОДИ.",
  },
  {
    id: "naoh",
    categoryId: "acids_bases",
    invCategory: "reagent",
    name: "Натрій гідроксид (NaOH)",
    nameEn: "Sodium Hydroxide (NaOH), pellets or solution",
    emoji: "⚗️",
    casNumber: "1310-73-2",
    description: "Сильна основа. Для нейтралізації, pH-корекції, гідролізу.",
    hazardClass: "corrosive",
    storageConditions: "RT (гранули), суха шафа. Розчин — RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
    notes: "Гігроскопічний. Зберігати щільно закритим. 10М — стандартний стоковий.",
  },
  {
    id: "acetic_acid",
    categoryId: "acids_bases",
    invCategory: "reagent",
    name: "Оцтова кислота (льодяна)",
    nameEn: "Acetic Acid, Glacial",
    emoji: "⚗️",
    casNumber: "64-19-7",
    description: "Слабка органічна кислота. Для буферів (ацетатний буфер), фіксації, фарбування гелів.",
    hazardClass: "flammable",
    storageConditions: "RT, витяжна шафа, вогнезахисна шафа",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
    notes: "Різкий запах при концентраціях >1%. Спалах при 39°C.",
  },
  {
    id: "koh",
    categoryId: "acids_bases",
    invCategory: "reagent",
    name: "Калій гідроксид (KOH)",
    nameEn: "Potassium Hydroxide (KOH)",
    emoji: "⚗️",
    casNumber: "1310-58-3",
    description: "Сильна основа, краща розчинність у спиртах порівняно з NaOH.",
    hazardClass: "corrosive",
    storageConditions: "RT, суха шафа",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
  },
  {
    id: "hno3_65",
    categoryId: "acids_bases",
    invCategory: "reagent",
    name: "Нітратна кислота 65% (азотна)",
    nameEn: "Nitric Acid 65%",
    emoji: "⚗️",
    casNumber: "7697-37-2",
    description: "Для мінералізації зразків перед ААС та ІСП-МС. Окисник.",
    hazardClass: "oxidizing",
    storageConditions: "Кислотна шафа, окремо від органіки",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich (Suprapur)", "Merck", "VWR"],
    notes: "Сильний окисник. Реагує з органічними сполуками.",
  },

  // ── ОРГАНІЧНІ РОЗЧИННИКИ ──────────────────────────────────────────────────────
  {
    id: "methanol",
    categoryId: "solvents",
    invCategory: "reagent",
    name: "Метанол (МеОН)",
    nameEn: "Methanol (MeOH)",
    emoji: "🧴",
    casNumber: "67-56-1",
    description: "Розчинник для ВЕРХ, мембранного фарбування, хімічного синтезу, екстракції.",
    hazardClass: "toxic",
    storageConditions: "Вогнезахисна шафа, T<30°C",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Merck", "Roth", "VWR"],
    notes: "Токсичний при вдиханні та через шкіру. Метаболізується до мурашиної кислоти.",
  },
  {
    id: "ethanol_96",
    categoryId: "solvents",
    invCategory: "reagent",
    name: "Етанол 96% (Етиловий спирт)",
    nameEn: "Ethanol 96%",
    emoji: "🧴",
    casNumber: "64-17-5",
    description: "Дезінфектант, розчинник, осаджувач нуклеїнових кислот. Широке застосування.",
    hazardClass: "flammable",
    storageConditions: "Вогнезахисна шафа, T<25°C",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem"],
    notes: "Спалах при 13°C. Зберігати далеко від відкритого вогню.",
  },
  {
    id: "isopropanol",
    categoryId: "solvents",
    invCategory: "reagent",
    name: "Ізопропанол (IPA, 2-пропанол)",
    nameEn: "Isopropanol / Isopropyl Alcohol (IPA)",
    emoji: "🧴",
    casNumber: "67-63-0",
    description: "Дезінфектант, осаджувач ДНК/РНК, розчинник. Менш токсичний за метанол.",
    hazardClass: "flammable",
    storageConditions: "Вогнезахисна шафа",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "VWR"],
    notes: "Спалах при 12°C. Осадження ДНК — -20°C, 20 хв.",
  },
  {
    id: "acetonitrile",
    categoryId: "solvents",
    invCategory: "reagent",
    name: "Ацетонітрил (АЦН, ВЕРХ grade)",
    nameEn: "Acetonitrile, HPLC grade (ACN)",
    emoji: "🧴",
    casNumber: "75-05-8",
    description: "Розчинник для ВЕРХ, екстракції протеомних зразків (ACN/TFA), хімічного синтезу.",
    hazardClass: "flammable",
    storageConditions: "Вогнезахисна шафа, T<25°C",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich (HiPerSolv)", "Merck", "VWR", "Roth"],
    notes: "Спалах при 2°C. Помірно токсичний. ВЕРХ-grade — з сертифікатом аналізу.",
  },
  {
    id: "chloroform",
    categoryId: "solvents",
    invCategory: "reagent",
    name: "Хлороформ (трихлорметан)",
    nameEn: "Chloroform (Trichloromethane)",
    emoji: "🧴",
    casNumber: "67-66-3",
    description: "Для виділення нуклеїнових кислот (TRIzol), екстракції ліпідів (Bligh-Dyer).",
    hazardClass: "toxic",
    storageConditions: "T<25°C, темна шафа; захищати від світла (окислення до фосгену)",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Merck", "Roth"],
    notes: "Стабілізований 0.5–1% аміленом або EtOH. Токсичний, наркотичний ефект.",
  },
  {
    id: "dmso",
    categoryId: "solvents",
    invCategory: "reagent",
    name: "DMSO (Диметилсульфоксид)",
    nameEn: "Dimethyl Sulfoxide (DMSO)",
    emoji: "🧴",
    casNumber: "67-68-5",
    description: "Розчинник для нерозчинних у воді сполук. Додаток до ПЛР (3–10%). Кріопротектор.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "AppliChem", "Roth"],
    notes: "Переносить розчинені речовини через шкіру — не торкатися без рукавичок.",
  },
  {
    id: "acetone",
    categoryId: "solvents",
    invCategory: "reagent",
    name: "Ацетон",
    nameEn: "Acetone",
    emoji: "🧴",
    casNumber: "67-64-1",
    description: "Для очищення скляного посуду, осадження білків, хімічного синтезу.",
    hazardClass: "flammable",
    storageConditions: "Вогнезахисна шафа, T<25°C",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Roth", "VWR"],
  },
  {
    id: "diethyl_ether",
    categoryId: "solvents",
    invCategory: "reagent",
    name: "Діетиловий ефір",
    nameEn: "Diethyl Ether",
    emoji: "🧴",
    casNumber: "60-29-7",
    description: "Для екстракції гідрофобних сполук. Дуже леткий і легкозаймистий.",
    hazardClass: "flammable",
    storageConditions: "Вогнезахисна шафа, T<10°C, захищати від пероксидоутворення",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Merck", "Roth"],
    notes: "Утворює вибухонебезпечні пероксиди при тривалому зберіганні. Перевіряти тест-смужками.",
  },

  // ── БАРВНИКИ ─────────────────────────────────────────────────────────────────
  {
    id: "coomassie",
    categoryId: "dyes",
    invCategory: "reagent",
    name: "Кумасі Яскраво-Синій R-250",
    nameEn: "Coomassie Brilliant Blue R-250",
    emoji: "🎨",
    casNumber: "6104-59-2",
    description: "Для фарбування білків у ПААГ після SDS-PAGE. Стандарт денситометрії.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Bio-Rad", "Roth"],
  },
  {
    id: "ponceau_s",
    categoryId: "dyes",
    invCategory: "reagent",
    name: "Понсо S (Ponceau S)",
    nameEn: "Ponceau S Solution 0.1% in 5% Acetic Acid",
    emoji: "🎨",
    description: "Для тимчасового фарбування білків на нітроцелюлозних і PVDF мембранах.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "AppliChem"],
    notes: "Легко видаляється промивкою водою. Сумісний з імуноблотингом.",
  },
  {
    id: "dapi",
    categoryId: "dyes",
    invCategory: "reagent",
    name: "DAPI (ядерний барвник)",
    nameEn: "DAPI (4',6-Diamidino-2-phenylindole)",
    emoji: "🎨",
    casNumber: "28718-90-3",
    description: "Флуоресцентний барвник для ядер ДНК (збудження 360 нм, емісія 460 нм).",
    hazardClass: "none",
    storageConditions: "-20°C, темне місце",
    defaultUnit: "мкл",
    manufacturers: ["Thermo Fisher (Invitrogen)", "Sigma-Aldrich", "Roche"],
    notes: "Проникає через клітинну мембрану тільки у фіксованих клітинах (чи при тривалій інкубації).",
  },
  {
    id: "propidium_iodide",
    categoryId: "dyes",
    invCategory: "reagent",
    name: "Йодид пропідію (PI)",
    nameEn: "Propidium Iodide (PI)",
    emoji: "🎨",
    casNumber: "25535-16-4",
    description: "Флуоресцентний інтеркалюючий барвник. Маркер мертвих клітин у проточній цитометрії.",
    hazardClass: "toxic",
    storageConditions: "+4°C, темне місце",
    defaultUnit: "мкл",
    manufacturers: ["Thermo Fisher", "Sigma-Aldrich", "BD Biosciences"],
    notes: "Не проникає у живі клітини. Мутаген — відходи утилізувати як токсичні.",
  },
  {
    id: "trypan_blue",
    categoryId: "dyes",
    invCategory: "reagent",
    name: "Трипановий синій (0.4%)",
    nameEn: "Trypan Blue 0.4% Solution",
    emoji: "🎨",
    casNumber: "72-57-1",
    description: "Барвник для визначення живих/мертвих клітин (метод виключення). Hemocytometer.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Gibco/Thermo Fisher"],
  },
  {
    id: "crystal_violet",
    categoryId: "dyes",
    invCategory: "reagent",
    name: "Кристалічний фіолетовий",
    nameEn: "Crystal Violet (Gentian Violet)",
    emoji: "🎨",
    casNumber: "548-62-9",
    description: "Для фарбування бактерій (Gram-фарбування), грибів, колоній клітин.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "AppliChem"],
  },

  // ── АНТИБІОТИКИ ───────────────────────────────────────────────────────────────
  {
    id: "ampicillin",
    categoryId: "antibiotics",
    invCategory: "reagent",
    name: "Ампіцилін",
    nameEn: "Ampicillin sodium salt",
    emoji: "💊",
    casNumber: "69-52-3",
    description: "Бета-лактамний антибіотик для селекції бактерій з pUC/pBluescript плазмідами.",
    hazardClass: "none",
    storageConditions: "-20°C (порошок), +4°C (100 мг/мл розчин, до 1 місяця)",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem"],
    notes: "Робоча концентрація: 100 мкг/мл. Не стабільний у культуральних середовищах >24 год.",
  },
  {
    id: "kanamycin",
    categoryId: "antibiotics",
    invCategory: "reagent",
    name: "Канаміцин",
    nameEn: "Kanamycin sulfate",
    emoji: "💊",
    casNumber: "25389-94-0",
    description: "Аміноглікозидний антибіотик для селекції з kanamycin-стійкими плазмідами.",
    hazardClass: "none",
    storageConditions: "-20°C (50 мг/мл стоковий)",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Thermo Fisher"],
    notes: "Робоча концентрація: 25–50 мкг/мл (E. coli).",
  },
  {
    id: "chloramphenicol",
    categoryId: "antibiotics",
    invCategory: "reagent",
    name: "Хлорамфенікол",
    nameEn: "Chloramphenicol",
    emoji: "💊",
    casNumber: "56-75-7",
    description: "Антибіотик для посилення виробництва плазмідної ДНК (амплікація) та відбору.",
    hazardClass: "toxic",
    storageConditions: "-20°C (розчин в EtOH 34 мг/мл)",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth"],
    notes: "Робоча концентрація: 34 мкг/мл. Токсичний, потенційний мутаген.",
  },
  {
    id: "hygromycin",
    categoryId: "antibiotics",
    invCategory: "reagent",
    name: "Гігроміцин B",
    nameEn: "Hygromycin B",
    emoji: "💊",
    description: "Антибіотик для відбору ссавців і дріжджів, трансфікованих hygromycin-стійким геном.",
    hazardClass: "toxic",
    storageConditions: "+4°C",
    defaultUnit: "мл",
    manufacturers: ["Thermo Fisher (Invitrogen)", "Sigma-Aldrich", "Roth"],
    notes: "Робоча концентрація: 100–500 мкг/мл (залежно від лінії).",
  },
  {
    id: "puromycin",
    categoryId: "antibiotics",
    invCategory: "reagent",
    name: "Пуроміцин",
    nameEn: "Puromycin dihydrochloride",
    emoji: "💊",
    casNumber: "58-58-2",
    description: "Антибіотик для відбору стабільних трансфектантів з пуроміцин-стійким геном.",
    hazardClass: "toxic",
    storageConditions: "-20°C",
    defaultUnit: "мкл",
    manufacturers: ["Sigma-Aldrich", "Thermo Fisher", "AppliChem"],
    notes: "Робоча концентрація: 1–10 мкг/мл. Дуже швидкий відбір (1–3 дні).",
  },
  {
    id: "zeocin",
    categoryId: "antibiotics",
    invCategory: "reagent",
    name: "Зеоцин™",
    nameEn: "Zeocin™ (Phleomycin D1)",
    emoji: "💊",
    description: "Для відбору в E. coli, дріжджах та ссавцях. Унікальний серед антибіотиків відбору.",
    hazardClass: "toxic",
    storageConditions: "-20°C, захищати від світла",
    defaultUnit: "мл",
    manufacturers: ["Thermo Fisher (Invitrogen)"],
    notes: "Робоча концентрація: 25–50 мкг/мл (E. coli), 100–200 мкг/мл (ссавці).",
  },

  // ── ПОЖИВНІ СЕРЕДОВИЩА ────────────────────────────────────────────────────────
  {
    id: "lb_broth",
    categoryId: "media",
    invCategory: "reagent",
    name: "LB бульйон (Lysogeny Broth)",
    nameEn: "LB Broth (Lysogeny / Luria-Bertani Broth)",
    emoji: "🧫",
    description: "Стандартне поживне середовище для культивування E. coli та інших бактерій.",
    hazardClass: "none",
    storageConditions: "RT (порошок); +4°C (готовий, стерилізований)",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem", "BD Difco"],
    notes: "Склад: триптон 10 г/л + дріжджовий екстракт 5 г/л + NaCl 10 г/л. Автоклав 121°C, 20 хв.",
  },
  {
    id: "lb_agar",
    categoryId: "media",
    invCategory: "reagent",
    name: "LB Агар",
    nameEn: "LB Agar (Lysogeny Broth + Agar)",
    emoji: "🧫",
    description: "Для вирощування бактерій на чашках Петрі. LB + агар 15 г/л.",
    hazardClass: "none",
    storageConditions: "RT (порошок); +55°C (розплавлений); +4°C (застиглий у чашках)",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "BD Difco", "AppliChem"],
    notes: "Антибіотики додавати охолодженим до 50°C агаром. Чашки зберігати в холодильнику до 2 місяців.",
  },
  {
    id: "soc_medium",
    categoryId: "media",
    invCategory: "reagent",
    name: "SOC середовище",
    nameEn: "SOC Medium (Super Optimal broth with Catabolite repression)",
    emoji: "🧫",
    description: "Збагачене відновне середовище для трансформації E. coli. Підвищує ефективність.",
    hazardClass: "none",
    storageConditions: "+4°C (стерилізоване фільтруванням)",
    defaultUnit: "мл",
    manufacturers: ["Thermo Fisher (Invitrogen)", "Sigma-Aldrich", "New England Biolabs"],
    notes: "Не автоклавувати (розклад цукрів). Фільтрація 0.22 мкм.",
  },
  {
    id: "yeast_extract",
    categoryId: "media",
    invCategory: "reagent",
    name: "Дріжджовий екстракт",
    nameEn: "Yeast Extract",
    emoji: "🧫",
    description: "Компонент поживних середовищ. Джерело вітамінів, амінокислот та пептидів.",
    hazardClass: "none",
    storageConditions: "RT, суха шафа",
    defaultUnit: "г",
    manufacturers: ["BD Difco", "Sigma-Aldrich", "Roth", "AppliChem"],
  },
  {
    id: "tryptone",
    categoryId: "media",
    invCategory: "reagent",
    name: "Триптон (пептон)",
    nameEn: "Tryptone / Bacteriological Peptone",
    emoji: "🧫",
    description: "Ферментативний гідролізат казеїну. Основний азотистий компонент поживних середовищ.",
    hazardClass: "none",
    storageConditions: "RT, суха шафа",
    defaultUnit: "г",
    manufacturers: ["BD Difco", "Sigma-Aldrich", "Roth"],
  },

  // ── СТАНДАРТИ ─────────────────────────────────────────────────────────────────
  {
    id: "protein_ladder_prestained",
    categoryId: "standards",
    invCategory: "standard",
    name: "Маркер молекулярної маси білків (передфарбований)",
    nameEn: "Prestained Protein Ladder / PageRuler",
    emoji: "📊",
    description: "Кольоровий маркер для SDS-PAGE та вестерн-блоту. Полоси у діапазоні 10–250 кДа.",
    hazardClass: "none",
    storageConditions: "-20°C",
    defaultUnit: "мкл",
    manufacturers: ["Thermo Fisher (PageRuler)", "Bio-Rad (Precision Plus)", "New England Biolabs"],
    notes: "Зберігати аліквоти по 50 мкл. Не нагрівати і не кип'ятити.",
  },
  {
    id: "dna_ladder_1kb",
    categoryId: "standards",
    invCategory: "standard",
    name: "ДНК Маркер 1 кб (GeneRuler)",
    nameEn: "DNA Ladder 1 kb (GeneRuler / HyperLadder)",
    emoji: "📊",
    description: "Маркер розміру ДНК-фрагментів для агарозного електрофорезу. 250 п.н.–10 кб.",
    hazardClass: "none",
    storageConditions: "-20°C або +4°C",
    defaultUnit: "мкл",
    manufacturers: ["Thermo Fisher (GeneRuler)", "New England Biolabs (1kb Plus)", "Bioline (HyperLadder)"],
  },
  {
    id: "bca_reagent",
    categoryId: "standards",
    invCategory: "standard",
    name: "BCA набір для визначення білка",
    nameEn: "BCA Protein Assay Kit",
    emoji: "📊",
    description: "Колориметричне визначення концентрації білка методом біцинхонінової кислоти.",
    hazardClass: "none",
    storageConditions: "RT (реагент A і B окремо)",
    defaultUnit: "мл",
    manufacturers: ["Thermo Fisher (Pierce BCA)", "Sigma-Aldrich", "Bio-Rad"],
    notes: "Стандарт BSA 0–2 мг/мл. Несумісний з SDS>0.1%, EDTA та відновниками.",
  },
  {
    id: "bradford_reagent",
    categoryId: "standards",
    invCategory: "standard",
    name: "Bradford реагент (Кумасі G-250)",
    nameEn: "Bradford Protein Assay Reagent (Coomassie G-250)",
    emoji: "📊",
    description: "Швидке колориметричне визначення білка. Λ = 595 нм. Менш чутливий до детергентів.",
    hazardClass: "none",
    storageConditions: "RT, захищати від світла",
    defaultUnit: "мл",
    manufacturers: ["Bio-Rad (Bradford)", "Sigma-Aldrich", "Thermo Fisher"],
  },
  {
    id: "ph_buffer_4",
    categoryId: "standards",
    invCategory: "standard",
    name: "pH Калібрувальний буфер pH 4.00",
    nameEn: "pH Calibration Buffer pH 4.00",
    emoji: "📊",
    description: "Стандартний буфер для двоточкового калібрування pH-метрів.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Hanna Instruments", "Thermo Fisher (Orion)", "Mettler Toledo", "WTW"],
    notes: "Замінювати після кожного калібрування. Не повертати у закриту пляшку.",
  },
  {
    id: "ph_buffer_7",
    categoryId: "standards",
    invCategory: "standard",
    name: "pH Калібрувальний буфер pH 7.00",
    nameEn: "pH Calibration Buffer pH 7.00",
    emoji: "📊",
    description: "Стандартний буфер для pH-метрів. Ізотонічний точці нульового потенціалу.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "мл",
    manufacturers: ["Hanna Instruments", "Thermo Fisher (Orion)", "Mettler Toledo", "WTW"],
  },

  // ── ВИТРАТНІ МАТЕРІАЛИ ────────────────────────────────────────────────────────
  {
    id: "tips_10ul",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "Наконечники 10 мкл (з фільтром)",
    nameEn: "Pipette Tips 10 µL, filtered, low retention",
    emoji: "📦",
    description: "Для прецизійного дозування малих об'ємів. Фільтр захищає від аерозолів (ДНК/РНК роботи).",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Eppendorf", "Sartorius", "Thermo Fisher", "Gilson"],
  },
  {
    id: "tips_200ul",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "Наконечники 200 мкл (жовті)",
    nameEn: "Pipette Tips 200 µL",
    emoji: "📦",
    description: "Стандартний жовтий наконечник для піпеток 20–200 мкл.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Eppendorf", "Sartorius", "Thermo Fisher", "Biosphere"],
  },
  {
    id: "tips_1000ul",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "Наконечники 1000 мкл (сині)",
    nameEn: "Pipette Tips 1000 µL",
    emoji: "📦",
    description: "Синій наконечник для піпеток 100–1000 мкл.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Eppendorf", "Sartorius", "Thermo Fisher"],
  },
  {
    id: "tubes_15ml",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "Центрифужні пробірки 15 мл (Falcon)",
    nameEn: "Conical Centrifuge Tubes 15 mL",
    emoji: "📦",
    description: "Поліпропіленові конічні пробірки для центрифугування, зберігання, культур клітин.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Corning (Falcon)", "Greiner Bio-One", "Sarstedt", "Thermo Fisher"],
    notes: "Автоклавовані або DNase/RNase-free варіанти — для молекулярної біології.",
  },
  {
    id: "tubes_50ml",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "Центрифужні пробірки 50 мл (Falcon)",
    nameEn: "Conical Centrifuge Tubes 50 mL",
    emoji: "📦",
    description: "Для збирання, зберігання та транспортування рідин у більших об'ємах.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Corning (Falcon)", "Greiner Bio-One", "Sarstedt"],
  },
  {
    id: "eppendorf_tubes_15",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "Мікропробірки 1.5 мл (Eppendorf)",
    nameEn: "Microcentrifuge Tubes 1.5 mL",
    emoji: "📦",
    description: "Стандартна мікропробірка для реакцій, зберігання та центрифугування.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Eppendorf", "Sarstedt", "Axygen", "Thermo Fisher"],
  },
  {
    id: "pcr_tubes_02",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "ПЛР пробірки 0.2 мл",
    nameEn: "PCR Tubes 0.2 mL (with domed cap)",
    emoji: "📦",
    description: "Тонкостінні пробірки для ПЛР реакцій у термоциклерах.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Eppendorf", "Bio-Rad", "Thermo Fisher", "Axygen"],
  },
  {
    id: "plate_96",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "96-лунковий планшет (flat bottom)",
    nameEn: "96-Well Microplate, flat-bottom, clear",
    emoji: "📦",
    description: "Для ELISA, клітинних культур, спектрофотометрії у планшетному форматі.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Corning", "Greiner Bio-One", "Nunc (Thermo Fisher)", "Sarstedt"],
    notes: "Black plates — для флуоресценції. White plates — для люмінесценції.",
  },
  {
    id: "gloves_nitrile",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "Рукавички нітрилові (S/M/L)",
    nameEn: "Nitrile Examination Gloves, powder-free",
    emoji: "📦",
    description: "Засіб індивідуального захисту. Стійкі до більшості хімічних реагентів.",
    hazardClass: "none",
    storageConditions: "RT, суха шафа",
    defaultUnit: "шт",
    manufacturers: ["Kimberly-Clark (Purple Nitrile)", "Ansell (TouchNTuff)", "VWR"],
    notes: "Замінювати при контакті з сильними розчинниками (ацетон, хлороформ руйнує нітрил).",
  },
  {
    id: "filter_022um",
    categoryId: "consumables",
    invCategory: "consumable",
    name: "Шприцеві фільтри 0.22 мкм (PES/PVDF)",
    nameEn: "Syringe Filters 0.22 µm",
    emoji: "📦",
    description: "Стерилізуюча фільтрація розчинів, видалення часток та мікроорганізмів.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "шт",
    manufacturers: ["Merck Millipore (Millex)", "Sartorius (Minisart)", "Thermo Fisher"],
    notes: "PES — для водних розчинів. PVDF — для органічних розчинників і ВЕРХ.",
  },

  // ── СОЛІ ТА РЕАКТИВИ ─────────────────────────────────────────────────────────
  {
    id: "nacl",
    categoryId: "salts",
    invCategory: "reagent",
    name: "Натрій хлорид (NaCl, кухонна сіль)",
    nameEn: "Sodium Chloride (NaCl)",
    emoji: "🧪",
    casNumber: "7647-14-5",
    description: "Для фізіологічних розчинів, буферів, підтримання іонної сили.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
  },
  {
    id: "kcl",
    categoryId: "salts",
    invCategory: "reagent",
    name: "Калій хлорид (KCl)",
    nameEn: "Potassium Chloride (KCl)",
    emoji: "🧪",
    casNumber: "7447-40-7",
    description: "Компонент PBS, клітинних середовищ, електролітних розчинів.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
  },
  {
    id: "mgcl2",
    categoryId: "salts",
    invCategory: "reagent",
    name: "Магній хлорид (MgCl₂)",
    nameEn: "Magnesium Chloride hexahydrate (MgCl₂·6H₂O)",
    emoji: "🧪",
    casNumber: "7791-18-6",
    description: "Кофактор ДНК-полімераз і нуклеаз. Компонент ПЛР-буферів (1.5–2.5 мМ).",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem"],
    notes: "1М стоковий розчин стерилізувати фільтруванням або автоклавом.",
  },
  {
    id: "cacl2",
    categoryId: "salts",
    invCategory: "reagent",
    name: "Кальцій хлорид (CaCl₂)",
    nameEn: "Calcium Chloride dihydrate (CaCl₂·2H₂O)",
    emoji: "🧪",
    casNumber: "10035-04-8",
    description: "Для трансформації E. coli, буферів, середовищ. Компонент компетентних клітин.",
    hazardClass: "none",
    storageConditions: "RT, захищати від вологи",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
  },
  {
    id: "na2hpo4",
    categoryId: "salts",
    invCategory: "reagent",
    name: "Натрій фосфат двозаміщений (Na₂HPO₄)",
    nameEn: "Sodium Phosphate Dibasic (Na₂HPO₄)",
    emoji: "🧪",
    casNumber: "7558-79-4",
    description: "Компонент PBS та фосфатних буферів. Регулятор pH у лужній зоні.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
  },
  {
    id: "kh2po4",
    categoryId: "salts",
    invCategory: "reagent",
    name: "Калій фосфат однозаміщений (KH₂PO₄)",
    nameEn: "Potassium Phosphate Monobasic (KH₂PO₄)",
    emoji: "🧪",
    casNumber: "7778-77-0",
    description: "Компонент PBS та фосфатних буферів. Регулятор pH у кислій зоні.",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "Merck"],
  },
  {
    id: "imidazole",
    categoryId: "salts",
    invCategory: "reagent",
    name: "Імідазол",
    nameEn: "Imidazole",
    emoji: "🧪",
    casNumber: "288-32-4",
    description: "Елюент для очищення His-tagged білків на Ni-NTA колонках (IMAC).",
    hazardClass: "none",
    storageConditions: "RT",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem"],
    notes: "Градієнт 20–500 мМ для елюції His-tag білків. Знімає поглинання на 280 нм.",
  },
  {
    id: "iptg",
    categoryId: "salts",
    invCategory: "reagent",
    name: "ІПТГ (ізопропіл-β-D-тіогалактопіранозид)",
    nameEn: "IPTG (Isopropyl β-D-1-thiogalactopyranoside)",
    emoji: "🧪",
    casNumber: "367-93-1",
    description: "Індуктор lac-оперону. Для індукції рекомбінантної експресії білків у E. coli.",
    hazardClass: "none",
    storageConditions: "-20°C (1М розчин аліквотами)",
    defaultUnit: "г",
    manufacturers: ["Sigma-Aldrich", "Roth", "AppliChem", "Gold Biotechnology"],
    notes: "Робоча концентрація: 0.1–1 мМ. 1М стоковий у воді аліквотами при -20°C.",
  },
  {
    id: "h2o2_30",
    categoryId: "salts",
    invCategory: "reagent",
    name: "Пероксид водню 30% (Гідроген пероксид)",
    nameEn: "Hydrogen Peroxide 30% (H₂O₂)",
    emoji: "🧪",
    casNumber: "7722-84-1",
    description: "Окисник для ECL-вестерн-блоту, дезінфекції, хімічних реакцій.",
    hazardClass: "oxidizing",
    storageConditions: "+4°C, темна пляшка, окремо від органіки",
    defaultUnit: "мл",
    manufacturers: ["Sigma-Aldrich", "Merck", "Roth"],
    notes: "Розкладається під дією світла та металів. Оновлювати щорічно.",
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
export function getReagentsByCategory(categoryId: string): ReagentCatalogItem[] {
  if (categoryId === "all") return REAGENT_ITEMS;
  return REAGENT_ITEMS.filter(i => i.categoryId === categoryId);
}

export function searchReagentCatalog(query: string): ReagentCatalogItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return REAGENT_ITEMS;
  return REAGENT_ITEMS.filter(i =>
    i.name.toLowerCase().includes(q) ||
    i.nameEn.toLowerCase().includes(q) ||
    i.description.toLowerCase().includes(q) ||
    (i.casNumber || "").includes(q) ||
    i.manufacturers.some(m => m.toLowerCase().includes(q))
  );
}
